### ISSUE TITLE
Unable to acquire bus name 'org.gnome.Pomodoro'

### ISSUE THREAD

**Issue by jcelliott** [codito/gnome-pomodoro#123]
I get this error on GNOME 3.10:

`** (gnome-pomodoro:12617): CRITICAL **: main.vala:65: Unable to acquire bus name 'org.gnome.Pomodoro'`

Any ideas what might be wrong?

**Comment by dparrova** [comment]
Hi Kamilprusko, I have the same problem, I did try remove pomodoro@arun.codito.in from ~/.local/share/gnome-shell/extensions, but the folder dosn't exist, actually I use ubuntu 14.04 with Unity.
