### ISSUE TITLE
gnome-shell 3.12

### ISSUE THREAD

**Issue by oktayacikalin** [codito/gnome-pomodoro#129]
Please implement support for gnome-shell 3.12.

I'm getting the following error:

```
$ cat gnome-shell.log | grep -i pomo
(gnome-shell:17264): Gjs-CRITICAL **: JS ERROR: Exception in callback for signal: extension-found: SyntaxError: syntax error @ /usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/dbus.js:27
```

I'm using the git repo with hash: 453a73cdfd17071d009baae71256d810ce292eb8

**Comment by vortexnix** [comment]
@dotsdl, I am having the same issue as you mentioned. the idle setting of the pomodoro dosent seem to work. Has it been fixed ?
