### ISSUE TITLE
Unable to compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by gluesniffmonkey** [codito/gnome-pomodoro#133]
I am trying to compile gnome-shell-pomodoro on Ubuntu 14.04. It is giving the following error.

Is there a way to fix? 

Thanks for your time.

Requested 'gnome-desktop-3.0 >= 3.10.0' but version of gnome-desktop-3.0 is 3.8.4

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GNOME_POMODORO_CFLAGS
and GNOME_POMODORO_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
felixdz@gUn:~/Downloads/codito-gnome-shell-pomodoro-f084ebc$ gnome-shell --version
GNOME Shell 3.10.4

**Comment by kamilprusko** [comment]
Thanks @aerostitch.

Packages are in stable Ubuntu repos. I've added download info on http://gnomepomodoro.org/

This issue is outdated so I'm closing it.
