### ISSUE TITLE
No bell sound

### ISSUE THREAD

**Issue by pwl** [codito/gnome-pomodoro#136]
I have been using this extension for more than a year now and I am yet to hear the bell sounds associated to finishing and starting of pomodoro.  I am now using Archlinux with gnome 3.12.1 and gnome-shell-pomodoro version 10.1.  All of the sound files are in place

```
$ ls -l /usr/share/gnome-pomodoro/sounds/ 
total 5772
-rw-r--r-- 1 root root    8921 05-05 09:06 bell.ogg
-rw-r--r-- 1 root root 5579242 05-05 09:06 birds.ogg
-rw-r--r-- 1 root root  168981 05-05 09:06 clock.ogg
-rw-r--r-- 1 root root   21087 05-05 09:06 loud-bell.ogg
-rw-r--r-- 1 root root  117146 05-05 09:06 timer.ogg
```

I can hear the Timer Ticking/Woodland Birds/Clock Ticking during pomodoro, but there is no sound when pomodoro is starting/stopping (despite the volume levels being set to maximum).

**Comment by kamilprusko** [comment]
Turns out if media role for the sound is set to "alert", then it's played despite muted sounds in system settings.
Fixed in 21e8ab7fba6d897b2d0b481233c1ea617c93d0ea
