### ISSUE TITLE
Prevent Gnome to block screen when break

### ISSUE THREAD

**Issue by Ecron** [codito/gnome-pomodoro#142]
When I'm in a long 15 minutes break, system blocks screen (because I've configured it), but it's annoying because it doesn't notifies when the break is over.

So please prevent system to block screen when inactivity if there's a break  (and the full screen notification and timer is displayed). :smile:

**Comment by kamilprusko** [comment]
Notifications now show up on screen shield (not immediately). When pomodoro starts it wakes the screen.
