### ISSUE TITLE
Drop font dependencies from packages

### ISSUE THREAD

**Issue by PanderOpenTaal** [codito/gnome-pomodoro#150]
Please drop font dependencies google-droid-sans-fonts and google-droid-fonts from RPM packages and fonts-droid from DEB packages.

Some font power users and TeX Live users have other sources for fonts which is outside of the package managers. Although many software needs specific fonts to be present, it is not absolutely necessary.

Therefore either remove the dependencies of change them into suggested packages. Most users will have them installed anyway and in this way it is decreasing font related package cluttering.

**Comment by PanderMusubi** [comment]
Nevertheless, it gets installed automatically even though it is only recommend. Which is not helping reducing font dependencies. Most users do not install and explicitly indicate to omit the recommendations. Sorry to get bakc on this one, but for advanced users of font, this is a bit of a nuisance, while for common users this is not a recommended dependency that they are going to miss. Font dependencies or recommendation, in general, should be avoided.

    $ apt-cache show gnome-shell-pomodoro-data|grep droid
    Recommends: fonts-droid
