### ISSUE TITLE
More control over sound

### ISSUE THREAD

**Issue by PanderMusubi** [codito/gnome-pomodoro#151]
Could you please offer:
* menu item to test sound
* bypass GNOME Sound Effects - Alert Volume (I don't want other sound effects as they distract me and that is against the Pomodoro Method® ;-) )
* menu item to change sound (choose custom wav/pm3/ogg file or go back to default sound)
* in stead of sound on/off as what is implemented now, provide settings for sound for:
  * start of pomodoro (none/default/custom) one could use a motivational sound
  * end of pomodoro (none/default/custom) one could use a rewarding sound

**Comment by kamilprusko** [comment]
Points:
* menu item to test sound
* menu item to change sound (choose custom wav/pm3/ogg file or go back to default sound)

are done in master branch. Preview is not perfect, need to add files to the list to preview, but it's better then what was before.

![pomodoro-sound-chooser](https://cloud.githubusercontent.com/assets/1135423/14796831/aab27ec0-0b2f-11e6-8bd1-b81f71b35949.png)

**Comment by krchat** [comment]
Fedora 25.  I checked my system settings
$ canberra-gtk-play --file=/usr/share/gnome-pomodoro/sounds/loud-bell.ogg --volume=1.0
the sound - On.
I added my ogg file to Start Break sound. If I click on it - it plays well, but sound doesn't start from pomodoro timer.
