### ISSUE TITLE
Font color running pomodoro

### ISSUE THREAD

**Issue by PanderMusubi** [codito/gnome-pomodoro#156]
Please allow setting font color of running pomodoro. Once I have mistakenly used the pomodoro time for the actual time :confused: 

The most simple implementation would be that, via an checkbox option, the running timer has the same grey font color as an inactive timer.

**Comment by alexandre-mbm** [comment]
Put the circle icon at bar and put the time between the timer's label and the button.

**Comment by kamilprusko** [comment]
It's in the latest release.
