### ISSUE TITLE
Gnome shell Notifications break with this extension

### ISSUE THREAD

**Issue by rajeshksv** [codito/gnome-pomodoro#158]
After installing this extension, notifications from other extensions break. I can hear the sound of other notifications, but can't see them. I have to disable this extension , refresh gnome shell (alt+F2 , r) to get back my notifications from other extensions. Please fix this.

PS : Its a wonderful and must have extension!

I am running . Gnome shell 3.12 on Ubuntu Gnome 14.04. Let me know if I can provide you more info

**Comment by RageZBla** [comment]
+1
