### ISSUE TITLE
Gnome 3.14 Status inconsistencies

### ISSUE THREAD

**Issue by saamalik** [codito/gnome-pomodoro#162]
When the pomodoro starts, "Notifications" is switched off (as expected) but the status reported by Empathy is still "Available" (expected to be Busy). This used to work fine with Gnome 3.12

Arch
Installed using [AUR](https://aur.archlinux.org/packages/gnome-shell-pomodoro/)

**Comment by kamilprusko** [comment]
It's in new released version for GNOME 3.14 & 3.16... I could say, finally.
