### ISSUE TITLE
Arch Linux install error

### ISSUE THREAD

**Issue by KeNaCo** [codito/gnome-pomodoro#166]
makepkg return:
curl: (22) The requested URL returned error: 404 Not Found

**Comment by michalrus** [comment]
@KeNaCo, how did you come up with an idea that this is upstream’s fault? :-( Just bad packaging. Use the `gnome-shell-pomodoro-git` package → https://aur.archlinux.org/packages/gnome-shell-pomodoro-git/ .

**Comment by KeNaCo** [comment]
I know this is package problem but I dont know who create package, if you or somebody else.. so I simply wrote msg on both places..

**Comment by haaja** [comment]
I am assuming this issue has been closed? It was not an upstream issue but simply github changing the URL they serve packages without notice.

**Comment by kamilprusko** [comment]
Yes @haaja. This issue has been resolved
https://aur.archlinux.org/packages/gnome-shell-pomodoro/
