### ISSUE TITLE
Time doesn't tick

### ISSUE THREAD

**Issue by vidmantas** [codito/gnome-pomodoro#167]
Hello, 

when I start the timer, the time does not change. However if I enable/disable the plugin, time shows up with updated value. 

FC21, installed from repo gnome-shell-extension-pomodoro-0.11.0-0.1.git656e0643.fc21.x86_64.rpm

**Comment by vidmantas** [comment]
Sorry, after I have tried to re-login, this issue seems to be solved (might be worth noticing in Readme maybe?)

**Comment by kamilprusko** [comment]
Thanks @vidmantas for your report. Did it happen with gnome-shell 3.14.2 or earlier? I've already spent some time tracing this bug, and it seemed to be solved with 3.14.1.

I should add a dialog offering to restart gnome-shell if that happens, just in case.

**Comment by vidmantas** [comment]
Gnome version 3.14.2

**Comment by kamilprusko** [comment]
I'll look into that. Thanks!

**Comment by kamilprusko** [comment]
In 3.14 problem seemed to to be related with DBus and notifying about changed properties... but I can't reproduce it in 3.16, and couldn't in earlier versions. If it happens fell free to reopen this issue.
