### ISSUE TITLE
Support for Gnome 3.16

### ISSUE THREAD

**Issue by jpfender** [codito/gnome-pomodoro#175]
In gnome 3.16, when starting gnome-pomodoro from the command line, I get:

```
** (gnome-pomodoro:20275): CRITICAL **: pomodoro_sounds_construct: assertion 'timer != NULL' failed

** (gnome-pomodoro:20275): CRITICAL **: pomodoro_presence_construct: assertion 'timer != NULL' failed

** (gnome-pomodoro:20275): CRITICAL **: pomodoro_power_construct: assertion 'timer != NULL' failed

** (gnome-pomodoro:20275): CRITICAL **: pomodoro_screen_saver_construct: assertion 'timer != NULL' failed

** (gnome-pomodoro:20275): CRITICAL **: pomodoro_gnome_desktop_construct: assertion 'timer != NULL' failed

(gnome-pomodoro:20275): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gnome-pomodoro:20275): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gnome-pomodoro:20275): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(gnome-pomodoro:20275): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (gnome-pomodoro:20275): CRITICAL **: pomodoro_timer_restore: assertion 'self != NULL' failed
```

In `gnome-tweak-tool`, the extension cannot be enabled and the warning message says "Extension does not support shell version". Simply adding "3.16" to the `shell-version` array in `metadata.json` doesn't work.

**Comment by kamilprusko** [comment]
Thanks

Looks like gnome-pomodoro fails to register a DBus service. Are you running the latest code from master branch? Does it happen every time? Does it still happen after you log out / reboot?

There is no 3.16 support in master yet. Try gnome-3.16 branch.

**Comment by jpfender** [comment]
I am running the version packaged in [AUR](https://aur.archlinux.org/packages/gnome-shell-pomodoro/), which is 0.10.3-3.

I can reliably reproduce the crash, and logging out or rebooting doesn't help either.

**Comment by michalrus** [comment]
@jpfender I’m running `gnome-shell-pomodoro-git` from AUR, too, but I’ve modified the `PKGBUILD` to use `#branch=gnome-3.16`. The version I’m running now is:

    gnome-shell-pomodoro-git r649.c7ad79d-1

**Comment by all3fox** [comment]
@jpfender @michalrus thank you for this discussion.

I tried `gnome-shell-pomodoro-git` from the AUR, changed the line in `PKGBUILD`

```diff
- source=("$pkgname"::'git+https://github.com/codito/gnome-shell-pomodoro.git)
+ source=("$pkgname"::'git+https://github.com/codito/gnome-shell-pomodoro.git#branch=gnome-3.16')
```
and once installed, restarted `gnome-shell` with `Alt+F2 r Enter`. Everything seems to work now.

**Comment by jpfender** [comment]
Thank you @michalrus and @all3fox, it works for me now!
