### ISSUE TITLE
Building on Ubuntu 15.04

### ISSUE THREAD

**Issue by joestrong** [codito/gnome-pomodoro#176]
While there isn't a package for Ubuntu 15.04, I've tried to build it myself.

The only dependancy I can't match is `gom-1.0 >= 0.2`

Is this the audio mixer package? I can install gom 0.30 from ubuntu's repos which didn't help, I expect I'm looking for a dev package, although I couldn't find one.

**Comment by kamilprusko** [comment]
No, it's a different gom package. [libgom](https://wiki.gnome.org/Projects/Gom) is an ORM based on gobject and sqlite... and I don't see a package for it in Ubuntu yet.

I've merged master branch into gnome-3.14. You should be able to build it without libgom now.

I'll try bulid new .deb package within few days.

**Comment by joestrong** [comment]
I can confirm that it builds for me now on 15.04
