### ISSUE TITLE
Error when timer starts

### ISSUE THREAD

**Issue by maicmarin** [codito/gnome-pomodoro#179]
After installing extension and trying to start the timer I get the following error:

```
Gjs-Message: JS LOG: Extension "pomodoro@arun.codito.in" had error:  GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.gnome.Pomodoro received signal 5
```

If I run gnome-pomodoro in terminal I get:

```
$ gnome-pomodoro

** (gnome-pomodoro:13752): WARNING **: gnome-desktop-module.vala:608: Error loading extension: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.gnome.Pomodoro received signal 5
GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.gnome.Pomodoro received signal 5
GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.gnome.Pomodoro received signal 5

^C
$
```

Preferences window appears but after closing window the program does not exit gracefully so I have to press CTLR+C to terminate it.

My linux box is ArchLinux with gnome 3.16.1

Best

**Comment by kamilprusko** [comment]
Hi @maicmarin, sorry for late response

When you close preferences dialog gnome-pomodoro somehow recieves a SIGTRAP (Trace/breakpoint trap) signal. You can run gnome-pomodoro inside a debugger to see what causes it:

    $ gdb gnome-pomodoro
    (gdb) run

I've tried that on Fedora inside a jhbuild and don't have that issue... If you still have it, try debugger.

Thanks

**Comment by all3fox** [comment]
Hello, @maicmarin, fellow Arch user here. If you grab the latest PKGBUILD from AUR (updated yesterday, 15.06.2015) you should be able to install fine. The checksums are messed up, however, so I suggest you ignore them. If that *doesn't work out* (which is unlikely), I suggest you take a look at issue #175 on how to modify your PKGBUILD script to grab the source from "gnome-3.16" brunch instead of "master".

**Comment by maicmarin** [comment]
Hi there,

Dear fellow Arch User @all3fox, I confirm gnome-pomodoro is now working great.

Lots of thanks.

Best to all,

M
