### ISSUE TITLE
make gnome-pomodoro.pot fails -- how to translate?

### ISSUE THREAD

**Issue by neitsab** [codito/gnome-pomodoro#180]
After moving to `gnome-shell-pomodoro-git` package from the [AUR](https://aur.archlinux.org/packages/gnome-shell-extension-pomodoro-git/) (which currently tracks the `gnome-3.16` branch), I tried to update the French translation for it by following the steps I had used and proposed before (#161) but it doesn't work anymore:

```make
$ make gnome-pomodoro.pot
make: *** No rule to make target '../lib/gnome-desktop.vala', needed by 'gnome-pomodoro.pot'.  Stop.
```

As a consequence make target `update-po` is also blocked:

```make
$ make update-po 
make gnome-pomodoro.pot
make[1]: Entering directory '/media/data/Documents/PC/git/gnome-shell-pomodoro/po'
make[1]: *** No rule to make target '../lib/gnome-desktop.vala', needed by 'gnome-pomodoro.pot'.  Stop.
make[1]: Leaving directory '/media/data/Documents/PC/git/gnome-shell-pomodoro/po'
Makefile:209: recipe for target 'update-po' failed
make: *** [update-po] Error 2
```
How does one generate the .pot file now?

It would be nice if the wiki could be updated with the correct procedure; I can make a PR if you put me on the way (maybe use `intltool` instead of `gettext`?).

Thanks!

**Comment by kamilprusko** [comment]
Hi Bastien :)

Fixed that in gnome-3.16 branch, I updated po/POTFILES.in file.

Makefile targets work again. Though, GNOME advises its projects to make translators able to update translations without compiling, and I think it's a sensible practice to follow.

I've updated wiki page. If you find it could be improved, PRs are welcome :)
https://github.com/codito/gnome-pomodoro/wiki/Translating

For updating existing translation you can use:

    $ cd po
    $ intltool-update fr

**Comment by neitsab** [comment]
Hi Kamil!

Thanks for this, I was successfully able to update the translation by following the new procedure (and appreciated the ease of use of `intltool-update` :).

I pushed it to #181, however I haven't updated the branch to reflect the latest changes in `gnome-3.16` (I understood this would require doing a `rebase` rather than a `pull`, changing the commit SHA and thus losing the link with the PR?).

However, I created (locally) a new branch tracking the latest changes on `gnome-3.16` and committed the updated translation on top of it. So I can make a new PR with this branch if you prefer :)

**Comment by neitsab** [comment]
I just did a `git rebase -i upstream/gnome-3.16` in my feature branch, fixup the two translation commits together and amended the date so that `git log` looks like this:

```
commit 35bd6d3d5bab1e6ade10c949062a623bb8bf4f29
Author: Bastien Traverse <bt@esrevart.net>
Date:   2015-05-20 17:12:01 +0200

    Update French translation

commit 91c867fc49fe667228421c52e48fb1a504085023
Author: Kamil Prusko <kamilprusko@gmail.com>
Date:   2015-05-20 00:09:36 +0200

    Update po/POTFILES.in

commit 658b64f4c3b6a0f49a8034022e792668ccc4122c
Author: Kamil Prusko <kamilprusko@gmail.com>
Date:   2015-05-15 20:00:00 +0200

    WIP
```
(only local, not pushed yet)

Would that be okay for you?

**Comment by kamilprusko** [comment]
Sure, it would be very good :)

As you've changed your previous commit, you'll need to force push to your fork

    $ git push -f origin gnome-3.16-french-translation

(force push can lead to lost commits, use with caution)

**Comment by neitsab** [comment]
Thanks a lot, that worked as a charm :-)
