### ISSUE TITLE
gnome-pomodoro first start --- no timer

### ISSUE THREAD

**Issue by all3fox** [codito/gnome-pomodoro#183]
I have previously been able to use this extension. Issue #164 looks exactly like mine: when doing the first start, I run `gnome-pomodoro` in terminal and the timer does not appear. I tried `Alt + F2` and `r` to reboot `gnome-shell` but without success. I have also fired up `gnome-tweak-tool` which says "Extension does not support shell version" next to the `gnome-pomodoro` extension. My gnome shell is
```
alex@tardis ~ % gnome-shell --version
GNOME Shell 3.16.2
```

And while I am on it, huge thanks to the developers, this is a nice little extension!

**Comment by kamilprusko** [comment]
Thanks! :)

You could've installed it from our master branch, which didn't have support for gnome-shell 3.16 yet. I needed some time to merge gnome-3.16 branch into master...

Try updating it / install again.

**Comment by all3fox** [comment]
Oh, sorry, completely forgot that I took part in discussing the fix for Arch linux in issue #175. The solution there works for now, while you are merging into the master branch. Keep up the good work!
