### ISSUE TITLE
Fix documentation regarding Ubuntu packages

### ISSUE THREAD

**Issue by PanderMusubi** [codito/gnome-pomodoro#184]
In the README there is a link to where to find Ubuntu packages, but only Fedora and SUSE packages can be found at that location. Please fix documentation or provide packages there.

**Comment by kamilprusko** [comment]
I know... I'm working on it.

I have some trouble compiling it on openSUSE build service
<pre>
[  182s] cd tests && make test
[  182s] make[2]: Entering directory '/usr/src/packages/BUILD/tests'
[  182s] ./tests
[  182s] gdk_mir_display_open
[  182s] Failed to connect to Mir: Failed to connect to server socket: No such file or directory
[  182s] Unable to init server: Could not connect: Connection refused
[  182s] 
[  182s] (tests:10846): Gtk-WARNING **: cannot open display: 
[  182s] Makefile:713: recipe for target 'test' failed
[  182s] make[2]: *** [test] Error 1
</pre>

**Comment by PanderMusubi** [comment]
Does xhost + and export DISPLAY help? Apparently your build server want to spawn a window.

**Comment by kamilprusko** [comment]
Thanks for the idea. I just disabled the tests, though Open Build Service docs suggest to add X11 dependency.

On http://gnomepomodoro.org/ there are now packages for 14.04, 14.10 and 15.04.

**Comment by PanderMusubi** [comment]
Thanks, also for updating the README.md. Hope to see then also to be offered ad update via the repositories form Ubuntu et al.

**Comment by PanderMusubi** [comment]
And http://gnomepomodoro.org doesn't list how to start the application for the first time so that it start automatically. That was in the previous version of README.md.
