### ISSUE TITLE
Error start

### ISSUE THREAD

**Issue by orlandocoelho** [codito/gnome-pomodoro#185]
rt:gnome-pomodoro(gnome-3.14) $ gnome-pomodoro

(gnome-pomodoro:8091): GLib-GIO-ERROR **: Settings schema 'org.gnome.shell' is not installed

Trace/breakpoint trap (imagem do núcleo gravada)

**Comment by kamilprusko** [comment]
Hi. Can you tell me more about your setup? It looks like you don't have gnome-shell installed, or at least that gnome-pomodoro can't see gnome-shell settings as if it's sandboxed.

Does

    $ gsettings list-recursively org.gnome.shell

exit with an error?

Can paste output of

    $ whereis gnome-pomodoro

?

**Comment by orlandocoelho** [comment]
Hello

Follow the data you requested.

rt:~$ gsettings list-recursively org.gnome.shell
org.gnome.shell enabled-extensions ['pomodoro@arun.codito.in']
org.gnome.shell command-history @as []
org.gnome.shell remember-mount-password false
org.gnome.shell always-show-log-out false
org.gnome.shell looking-glass-history @as []
org.gnome.shell app-picker-view uint32 0
org.gnome.shell disable-extension-version-validation false
org.gnome.shell development-tools true
org.gnome.shell favorite-apps ['ubiquity-gtkui.desktop', 'firefox.desktop', 'evolution.desktop', 'empathy.desktop', 'rhythmbox.desktop', 'shotwell.desktop', 'libreoffice-writer.desktop', 'nautilus.desktop', 'yelp.desktop']
org.gnome.shell.keyboard keyboard-type 'touch'
org.gnome.shell.keybindings toggle-message-tray ['<Super>m']
org.gnome.shell.keybindings open-application-menu ['<Super>F10']
org.gnome.shell.keybindings pause-resume-tweens @as []
org.gnome.shell.keybindings toggle-application-view ['<Super>a']
org.gnome.shell.keybindings focus-active-notification ['<Super>n']
org.gnome.shell.keybindings toggle-overview ['<Super>s']
org.gnome.shell.calendar show-weekdate false
rt:~$ whereis gnome-pomodoro
gnome-pomodoro: /usr/bin/gnome-pomodoro /usr/share/gnome-pomodoro

After taking a sudo apt-get install gnome-shell-extensions, I managed to run the gnome-settings pomodoro however just, can not see in operation or place to run a pomodoro

**Comment by kamilprusko** [comment]
Not sure what happened here, it should be fine.

I found similar issue
https://github.com/mank319/elementaryPlus/issues/42

maybe a reboot will help.

**Comment by orlandocoelho** [comment]
Thanks for your help

**Comment by kamilprusko** [comment]
You're welcome.

You may try installing new version (http://gnomepomodoro.org/) from packages.
