### ISSUE TITLE
[UBUNTU 15.04] unable to start app

### ISSUE THREAD

**Issue by bbonnesoeur** [codito/gnome-pomodoro#187]
hi,

app doesn't start. When I launch it by terminal I have this message :  

```gnome-pomodoro 

  ** (gnome-pomodoro:20979): CRITICAL **: main.vala:65: Unable to acquire bus name 'org.gnome.Pomodoro' ```

**Comment by kamilprusko** [comment]
Hi @bbonnesoeur  :)

Error says that gnome-pomodoro is already running (you may try killing it)

    $ killall gnome-pomodoro
    $ gnome-pomodoro

If there is pomodoro indicator in the top panel then it's expected.

If you don't see the indicator then extension is not compatible with your gnome-shell version... If so - do you use gnome3 PPA? Did you install package from Ubuntu repos or downloaded from http://gnomepomodoro.org? If you're using gnome3 PPA try uninstalling gnome-pomodoro and install package from our website.

Did it help?

In any case I should put a more descriptive message, and I guess it should quit if it's unable to enable the extension.

**Comment by bbonnesoeur** [comment]
Hi @kamilprusko,

and thanks for reply.

I think I have  gnome3 
```
apt-show-versions gnome-shell                                      
gnome-shell:amd64/vivid 3.14.4-0ubuntu1 uptodate
gnome-shell:i386 not installed
```
What means exactly PPA ?

I install it form logitheque softaware center. I also try to remove it and install from commmand line whitouh success. Nothing appear in task bar. I'm under Unity maybe it's the problem ? (I think it is according your comment on gnomepomodor.org)

**Comment by kamilprusko** [comment]
Well, this app will work only in GNOME Shell.

If you haven't tried GNOME desktop yet, you can select GNOME Shell or GNOME Shell Classic during login. I'm only suggesting it because you have it already installed, better [look it up](https://www.youtube.com/watch?v=7p8Prlu3owc) first.

Cheers,
Kamil

**Comment by bbonnesoeur** [comment]
hi @kamilprusko,

I have switched to gnome , thanks. (I use gnome-flashback to do it)
