### ISSUE TITLE
 Appindicator support

### ISSUE THREAD

**Issue by kamilprusko** [codito/gnome-pomodoro#188]
Pomodoro should fallback to Appindicator if not using GNOME Shell. We could fallback to GtkStatusIndicator but it's deprecated since Gtk+ 3.14.

**Comment by mancvso** [comment]
I know Gnome shell is really cool, but there are users of LXDE, XFCE and friends who would benefit from this app.

**Comment by kamilprusko** [comment]
Just added a fallback for notifications 270fbce068e532d5a5b49a86260ae814483ec2e4.

There is now a window and notifications, seems usable but not complete yet. There is no indicator, hotkey, reminders, or idle/activity detection yet.

**Comment by kamilprusko** [comment]
Appindicator support added in b3ae033f7b5695e24890a3ce743336f19401ee60

Appindicator doesn't handle symbolic icons or something equivalent. I've added icons for Ambiance and Radiance themes. To have proper theme support upvote bug:
https://bugs.launchpad.net/indicator-application/+bug/903819
