### ISSUE TITLE
gobject-introspection-1.0 is not installed

### ISSUE THREAD

**Issue by MadcapJake** [codito/gnome-pomodoro#191]
I'm trying to install from source (I tried the ubuntu PPA and that finishes installing but there's no extension in the gnome-shell extensions folder, tried your PPA, that said there was a broken pipe) and now I am getting a configure error that gobject-introspection-1.0 is not installed.  I've installed all the packages listed including the ones you reference in #132 and still getting the same error.  I can't find any reference to what versions are supported, but I'm trying to install the `gnome-3.16` branch.

**Comment by kamilprusko** [comment]
Hi @MadcapJake 

I guess you need to install *libgirepository1.0-dev*.

If it helps I will update instructions on http://gnomepomodoro.org/ ... Though I find it a little odd because it doesn't seem to be required to build a .deb package :)

**Comment by MadcapJake** [comment]
I tried installing that and still got the same error.  I finally was able to get a running version though.

For context, when I tried `sudo gdebi gnome-pomodoro_0.11.0-1_amd64.deb` and that didn't work, it gave me this error:
```bash
dpkg: error processing archive gnome-pomodoro_0.11.0-1_amd64.deb (--install):
 trying to overwrite '/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/stylesheet.css', which is also in package gnome-shell-pomodoro-data 0.10.3-1build1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
```
So I searched the internet for `trying to overwrite ... which is also in ...` and found a solution:
```bash
sudo dpkg -i --force-overwrite gnome-pomodoro_0.11.0-1_amd64.deb
```
This time when running it, the window popped right up!  I'll let you know if I run into any problems after installing it this way. Thanks for the reply though!

**Comment by cross-hello** [comment]
> 

The answer you posed solve problem. 
Thank you~
