### ISSUE TITLE
Do not show preferences at start

### ISSUE THREAD

**Issue by runcom** [codito/gnome-pomodoro#193]
Since I don't need to customize the preferences at every start and because I want Pomodoro always running, I added it in my startup application list, but when I login the Pomodoro app is started and the preferences window shows up. Is there a way to prevent this? I just want to have it running w/o showing me that window (I can always click on Preferences if I need to)
I'm running fedora 22 if it helps.
Thanks

**Comment by kamilprusko** [comment]
Hi. Sorry for so late response, forgot to reply :/

You could add a param 

    $ gnome-pomodoro --no-default-window

but gnome-pomodoro already auto-starts when you have enabled extension. Adding Pomodoro to startup applications will just bring its main window to the front.
