### ISSUE TITLE
Update installation instructions on website

### ISSUE THREAD

**Issue by jubalh** [codito/gnome-pomodoro#202]
On http://gnomepomodoro.org/ the installation instructions for Tumbleweed are AFAIK not right.
https://build.opensuse.org/package/show?project=GNOME:Apps&package=gnome-pomodoro
Shows that there is a devel project and that links to factory and will go into Tumbleweed. So it's already in the repo and you don't have to add your personal one in this case :-)

**Comment by kamilprusko** [comment]
Changed. I've also added a one-click-install method as it is on
http://software.opensuse.org/package/gnome-pomodoro?search_term=gnome-pomodoro

though it seems odd that Tumbleweed uses the same link as the Factory
http://software.opensuse.org/ymp/openSUSE:Factory/standard/gnome-pomodoro.ymp?base=openSUSE%3AFactory&query=gnome-pomodoro

is it ok?

**Comment by jubalh** [comment]
Almost :-)
The ymp/OneClick files you linked are right.
But the command
```
sudo zypper install gnome-pomodoro
```
works only for Tumbleweed.
All other (the versioned ones) need to add the repository before you can install it.

Also you could remove the `Factory` selection option, since it is the same as Tumbleweed.

Thank you :-)

**Comment by jubalh** [comment]
Perfect! Thank you!
