### ISSUE TITLE
keeps making break sound at break time instead of starting/stopping or changing the settings, can't stop it

### ISSUE THREAD

**Issue by octohedron** [codito/gnome-pomodoro#207]
Very annoying, is there a way to reset the applet or something? I'm on linux mint and tried to "remove" the applet and add it again but it keeps completely broken and making sounds and blocking the screen completely breaking gnome and making annoying sounds while i'm trying to work.

**Comment by kamilprusko** [comment]
Try ```killall gnome-pomodoro```, or open preferences and from the app-menu choose Quit.

Can you write step by step istructions how to reproduce it? Thanks.

**Comment by octohedron** [comment]
Just using it, pausing/unpausing, restarting the timer etc, now it's happening again, I would make you a gif to show you, it's completely broken, i can't pause it for example, keeps sounding the alarm even though is set at 25 minutes and only 3 minutes have passed and the time keeps runnig etc, you should test it further use it for longer periods of time and use all the functions and you will break it pretty easily.

**Comment by octohedron** [comment]
also, your fix killall gnome-pomodoro "No process found." on linux mint 17.3, so i'm stuck with a completely broken gnome, even if i mute the sound it would still show notifications so i have to restart my computer which in the middle of a work session is very inconvenient.

**Comment by kamilprusko** [comment]
Closing. Didn't reproduce it for all this time.
