### ISSUE TITLE
Can't compile gnome-3.14

### ISSUE THREAD

**Issue by iainhallam** [codito/gnome-pomodoro#208]
I'm on CentOS 7.2, with GNOME 3.14. Once I'd installed gnome-common and intltool, the autogen line runs:

```
./autogen.sh --prefix=/usr --datadir=/usr/share
```

However it fails after loads of work with:

```
checking pkg-config is at least version 0.22... yes
./configure: line 12439: syntax error near unexpected token `1.36.0'
./configure: line 12439: `GOBJECT_INTROSPECTION_REQUIRE(1.36.0)'
```

Do you know if this is another missing dependency? Is there a list of dependencies for building somewhere?

**Comment by kamilprusko** [comment]
Looks like you're missing a development package for gobject-introspection (gobject-introspection-devel). There is a list of dependencies on http://gnomepomodoro.org/ , you should follow instructions for Fedora 21

To get all dependencies:

    sudo yum install gnome-common intltool vala vala-tools glib2-devel gobject-introspection-devel gtk3-devel gnome-desktop3-devel libcanberra-devel dbus-glib-devel gstreamer1-devel telepathy-glib-devel google-droid-sans-fonts

after you installed that you'll need to run autogen.sh again.

**Comment by doergn** [comment]
Great works also with Red Hat 7.2! :+1:

**Comment by EdoPut** [comment]
I get the same error but the checklist in `configure.ac` should have caught this

```
PKG_CHECK_MODULES(GNOME_POMODORO, [
    glib-2.0 >= $GLIB_REQUIRED
    gio-2.0 >= $GLIB_REQUIRED
    gio-unix-2.0 >= $GLIB_REQUIRED
    gthread-2.0 >= $GLIB_REQUIRED
    gmodule-no-export-2.0 >= $GLIB_REQUIRED
    gtk+-3.0 >= $GTK_REQUIRED
    gsettings-desktop-schemas >= $GTK_REQUIRED
    gobject-introspection-1.0 >= $INTROSPECTION_REQUIRED
    libpeas-1.0 >= $LIBPEAS_REQUIRED_VERSION
])
```

moreover in Debian the package is named `gobject-introspection` so that may be the cause and it should be handled as a Debian bug in packaging

**Comment by kamilprusko** [comment]
@EdoPut, I guess your're trying to compile from ```master``` branch. Code in ```master``` branch requires GTK+ 3.18, so I don't think it will work on GNOME 3.14.

Please try [gnome-3.14](https://github.com/codito/gnome-pomodoro/tree/gnome-3.14) branch, grab a package from http://gnomepomodoro.org/ or install from Debian repos

    $ sudo apt-get install gnome-shell-pomodoro

**Comment by subhammridha** [comment]
Thanks for helping with the list of dependencies. But, I doubt it is provided on your website for the software. It would be really helpful to list these dependencies on the website.
