### ISSUE TITLE
Pomodoro does not display on Compiz

### ISSUE THREAD

**Issue by dcaled** [codito/gnome-pomodoro#211]
Hey! 

I've installed gnome-pomodoro and, although the program starts correctly on Gnome Classic, I can not open it using Compiz. I've checked and the process when I execute "gnome-pomodoro" is running.

My ubuntu release is 14.04 LTS 64-bit and I installed the package from the official website (http://gnomepomodoro.org/).

Do you have any idea what might be happening?
Thanks.

**Comment by kamilprusko** [comment]
You mean it doesn't work in Unity or XFCE?

Currently Pomodoro only works in GNOME Shell or Classic - it relies on the supplied extension. I'm working on a fallback mode, so that integration with GNOME will be optional. Then later I would like to add AppIndicator support for Unity. I expect to finish the first part around GNOME 3.20 release, this spring.

**Comment by dcaled** [comment]
I tried both XFCE and Gnome Flashback (Compiz and Metacity).
It just work when I use Gnome Classic. 
I guess you explained the reason and we'll have to wait until next release.

Thank you for the answer.

**Comment by pmontrasio** [comment]
With XDG_CURRENT_DESKTOP=GNOME-Flashback:Unity (Gnome Flashback with Compiz) the Preferences window appears and it works, but there is no way to do anything else.

**Comment by kamilprusko** [comment]
![gnome-pomodoro-window](https://cloud.githubusercontent.com/assets/1135423/15156385/1253092e-16e7-11e6-92c4-af4390335484.png)

Screenshot is from master branch. Fallback mode is usable, though there is no indicator yet. It still requires libgnome-desktop to compile and there are some bugs... overall it's getting there.

**Comment by kamilprusko** [comment]
Forgot to close. Packages with Unity / XFCE / Mate support are available in 16.10 repos.
