### ISSUE TITLE
Support for Fedora 24

### ISSUE THREAD

**Issue by myaskevich** [codito/gnome-pomodoro#216]
![gnome-shell-imgur-km3vfy](https://cloud.githubusercontent.com/assets/958221/14489826/0729faaa-0178-11e6-82fc-f38e10837df6.png)

**Comment by myaskevich** [comment]
Maybe if you told me what the procedure of upgrading to a newer gnome version boils down to, I'd try to do that myself.

**Comment by kamilprusko** [comment]
I see that the package hasn't been updated yet
https://apps.fedoraproject.org/packages/gnome-shell-extension-pomodoro/overview/

Uninstall your current package:

    $ sudo dnf remove gnome-shell-extension-pomodoro

and install from git:

    $ git clone -b gnome-3.20 https://github.com/codito/gnome-pomodoro.git
    $ cd gnome-pomodoro
    $ ./autogen.sh --prefix=/usr
    $ make
    $ sudo make install

Pomodoro should work after logging out / a reboot or after ```killall gnome-pomodoro``` and gnome-shell reload (Alt + F2 and "r").

For reference, instructions are on http://gnomepomodoro.org/.

**Comment by myaskevich** [comment]
Hi Kamil!

Thanks, that worked for me. Now I'm productive again!
But I'd prefer to keep the issue opened until fedora staff repackage a newer version of Pomodoro.

By the way, I couldn't find any instructions on http://gnomepomodoro.org/ site. Also I noticed [these instructions used to be in the project's README](https://github.com/codito/gnome-pomodoro/tree/gnome-3.12#installation), but not anymore.
If you need help on that just let me know.

**Comment by mbooth101** [comment]
A new update will hit the Fedora "updates-testing" repository soon: https://bodhi.fedoraproject.org/updates/FEDORA-2016-fbd83f89ac

Please consider leaving feedback.

BTW, the right place to report out-of-date version in Fedora would be the Red Hat bugzilla :-)

@kamilprusko Feel free to point users to our bugzilla if there is problem with the Fedora package: https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=gnome-shell-extension-pomodoro

**Comment by kamilprusko** [comment]
@mbooth101 Thanks :-)
