### ISSUE TITLE
Missing D-bus `NotifyPomodoroStart` signal

### ISSUE THREAD

**Issue by viccuad** [codito/gnome-pomodoro#217]
Hi, 

I'm trying to make an arduino+python listener to notify my colleagues on when I'm on a Pomodoro (akin to @glibersat 's [glibersat/pomarduino](https://github.com/glibersat/pomarduino), but for the new gnome-pomodoro instead).

I've been looking into gnome-pomodoro's D-bus interactions, and I have seen some mismatches.

Running `gdbus introspect --session --dest org.gnome.Pomodoro --object-path /org/gnome/Pomodoro` I see that it has `NotifyPomodoroEnd` and `NotifyPomodoroStart` signals:

```js
  interface org.gnome.Pomodoro {
    methods:
      ShowPreferences(in  s view,
                      in  u timestamp);
      Start();
      SetState(in  s state,
               in  d state_duration);
      Stop();
      Reset();
    signals:
      NotifyPomodoroEnd(b is_requested);
      NotifyPomodoroStart(b is_completed);
    properties:
      readonly d Elapsed = 1137.2586281299591;
      readonly d StateDuration = 1800.0;
      readonly d Session = 3.7886952405505712;
      readonly d SessionLimit = 4.0;
      readonly s State = 'pomodoro';
      readonly s Version = '0.11.0';
  };
```

But inspecting D-bus, I can't never see `org/gnome/Pomodoro` service send the `NotifyPomodoroStart` signal (yet I see the `NotifyPomodoroEnd`). For example, using `bustle` (and filtering to only the Shell and Pomodoro D-bus services), and starting and ending a Pomodoro, I get:

![bustle](https://cloud.githubusercontent.com/assets/2196685/14536111/25784fe4-0271-11e6-9c1b-1513cd27758e.png)

* Is that the intended behaviour, or is it missing the `NotifiyPomodoroStart` signal?
* Off-topic: Is there a beter D-bus way to get notified if we are on a Pomodoro? `org.freedesktop.DBus.Properties.PropertiesChanged` signal from `/org/gnome/Pomodoro` contains the `State` in the first second of a new state, eg: first second of a Pomodoro, first second of a Break, etc, but makes it convoluted to work with it. The same happens if you use Gnome-Shell's notifications.

Cheers.

**Comment by kamilprusko** [comment]
Yes, ```NotifiyPomodoroStart``` should be re-added. I'm not sure about the delay with properties change, gnome-shell extension uses it, it would be evident

From [extension/timer.js](https://github.com/codito/gnome-pomodoro/blob/gnome-3.20/extension/timer.js):

    _onPropertiesChanged: function(proxy, properties) {
        let state = proxy.State;

        if (this._state !== state) {
            this._state = state;
            this.emit('state-changed');
        }

        this.emit('update');
    },

```NotifiyPomodoroStart``` and ```NotifiyPomodoroEnd``` are for notifications and shouldn't really be used for watching state changes. It's more correct to watch for ```State``` property change, and it's better if you check other properties at the same time.

D-Bus interface will change in new version. From master branch:

      interface org.gnome.Pomodoro {
        methods:
          SetState(in  s name,
                   in  d timestamp);
          ShowPreferences(in  s page,
                          in  u timestamp);
          Start();
          Stop();
          Reset();
          Pause();
          Resume();
          Skip();
        signals:
          Destroy();
        properties:
          readonly d Elapsed = 830014.85099601746;
          readonly s State = 'null';
          readonly d StateDuration = 0.0;
          readonly b IsPaused = false;
          readonly s Version = '0.12.0';
      };

```State``` won't have value "idle", instead it will be "pomodoro" with ```IsPaused``` set to true. I should re-add ```NotifiyPomodoroStart``` and ```NotifiyPomodoroEnd``` but without params. Maybe I should add StateChanged signal too.

Thanks for the report. I'll fix this during weekend.

**Comment by viccuad** [comment]
Thanks for the extensive response.

FWIW, the Arduino thingy is complete now, [gomoduino](https://github.com/viccuad/gomoduino)

**Comment by kamilprusko** [comment]
I looked into this and ```NotifyPomodoroStart``` is taken quite literally - as if to notify with a popup or sound. It doesn't get emitted when it's caused by user action. Clearly it's a design issue.

In upcoming version there will be just ```StateChanged``` signal in place of ```NotifyPomodoroStart```  ```NotifyPomodoroEnd```, with info about current state and previous one 2b934794d2a72b72bd1f8344a3bb90740ec25605 . I think it will be saner.
