### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by DreaminginCodeZH** [codito/gnome-pomodoro#225]
I'm installing this extension from [AUR](https://aur.archlinux.org/packages/gnome-shell-pomodoro), on Arch Linux and GNOME 3.20.2.

I'm always seeing two notifications when the state of pomodoro changes. And there are also two full-screen countdowns appearing when break comes.

![2016-06-19 17-45-21](https://cloud.githubusercontent.com/assets/4469895/16176644/0f906c94-3646-11e6-853f-4a03358e1085.png)

(Another thing you can notice is that one of the notificatiosn is translated, while the other one is not.)

This is a regression since some last update, and before that it worked perfectly.

Do you have any idea on how to fix it?

**Comment by kamilprusko** [comment]
In new version there is now a fallback mode for other desktops or when not using the Shell extension. Looks like both modes are running :/

Does it happen every time? How can I reproduce it?

Restarting ```gnome-pomodoro``` should help

    killall gnome-pomodoro

**Comment by DreaminginCodeZH** [comment]
Sounds reasonable, there is perhaps some problem with the fallback mode detecting the extension's running?

Perhaps with GNOME 3.20.2 and gnome-pomodoro installed to `/usr/share/gnome-shell/extensions/` (the AUR package does this)? Or you can tell me how to attach some error logs, etc.

Killing gnome-pomodoro doesn't help - The extension then shows up as pomodoro is stopped, and when I start it from the extension menu, there are still two notifications. And I've rebooted my laptop a lot recents days but the bug persisted.

**Comment by kamilprusko** [comment]
Could you provide output of:

    $ dbus-send --session --type=method_call --print-reply --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Extensions.GetExtensionInfo string:"pomodoro@arun.codito.in"

**Comment by DreaminginCodeZH** [comment]
```
$ dbus-send --session --type=method_call --print-reply --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Extensions.GetExtensionInfo string:"pomodoro@arun.codito.in"
method return time=1466342650.306675 sender=:1.186 -> destination=:1.226 serial=819 reply_serial=2
   array [
      dict entry(
         string "uuid"
         variant             string "pomodoro@arun.codito.in"
      )
      dict entry(
         string "name"
         variant             string "Pomodoro"
      )
      dict entry(
         string "description"
         variant             string "A simple pomodoro timer"
      )
      dict entry(
         string "url"
         variant             string "http://gnomepomodoro.org"
      )
      dict entry(
         string "version"
         variant             string "0.12.0"
      )
      dict entry(
         string "type"
         variant             double 1
      )
      dict entry(
         string "state"
         variant             double 1
      )
      dict entry(
         string "path"
         variant             string "/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in"
      )
      dict entry(
         string "error"
         variant             string ""
      )
      dict entry(
         string "hasPrefs"
         variant             boolean false
      )
   ]
```

**Comment by kamilprusko** [comment]
Ok, more likely bug is in fallback switching logic, than in not recognizing extension.

I'll try reproduce it by writing a unit test.

Thanks!

**Comment by arashm** [comment]
I have same issues. Plus the overlay screen notification is also duplicated (it shows two counters on the screen), and also after the update to 0.12, the Pomodoro starts even if the system is idle, previously it was paused until I move mouse or take an action.

**Comment by smichel17** [comment]
I have the same issue.

```
$ dbus-send --session --type=method_call --print-reply --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Extensions.GetExtensionInfo string:"pomodoro@arun.codito.in"
method return time=1468419331.643187 sender=:1.15 -> destination=:1.72 serial=596 reply_serial=2
   array [
      dict entry(
         string "uuid"
         variant             string "pomodoro@arun.codito.in"
      )
      dict entry(
         string "name"
         variant             string "Pomodoro"
      )
      dict entry(
         string "description"
         variant             string "A simple pomodoro timer"
      )
      dict entry(
         string "url"
         variant             string "http://gnomepomodoro.org"
      )
      dict entry(
         string "version"
         variant             string "0.12.1"
      )
      dict entry(
         string "type"
         variant             double 1
      )
      dict entry(
         string "state"
         variant             double 1
      )
      dict entry(
         string "path"
         variant             string "/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in"
      )
      dict entry(
         string "error"
         variant             string ""
      )
      dict entry(
         string "hasPrefs"
         variant             boolean false
      )
   ]
```

**Comment by DreaminginCodeZH** [comment]
The issue has been resolved for me by updating the extension, please feel free to close it.

This extension has been really handy for me for a long time, thank you very much for your efforts!

**Comment by kamilprusko** [comment]
Thanks @DreaminginCodeZH for your help
