### ISSUE TITLE
Switcher position in shell popup

### ISSUE THREAD

**Issue by zagortenay333** [codito/gnome-pomodoro#226]
The switcher isn't properly aligned on the far left and it's driving me nuts :anguished: 
![screenshot from 2016-06-21 00-26-46](https://cloud.githubusercontent.com/assets/11144630/16212341/3d6434d2-3747-11e6-996b-7b6eea7c4f85.png)

Using gnome 3.20

**Comment by zagortenay333** [comment]
Present on all shell themes.

**Comment by kamilprusko** [comment]
I've tried newer version under gnome-shell 3.20, looks normal.

![screenshot from 2016-06-21 00-59-22](https://cloud.githubusercontent.com/assets/1135423/16212928/9e4867ba-374b-11e6-88cb-5568accc108c.png)

Does it work with the default theme for you?

**Comment by zagortenay333** [comment]
Eh, how did you install that? I seem to have a different version. Am on openSUSE

**Comment by kamilprusko** [comment]
For now you can install newer packages from http://gnomepomodoro.org/ , or from my [OBS](http://software.opensuse.org/download.html?project=home%3Akamilprusko&package=gnome-pomodoro).

@jubalh is preparing package for openSUSE repos, should land there eventually.

**Comment by jubalh** [comment]
@zagortenay333 The new release just came out a couple of days ago.
During free time I work on it at [https://build.opensuse.org/package/show?project=GNOME%3AApps&package=gnome-pomodoro](GNOME:APPS).
It will be there soon.

**Comment by jubalh** [comment]
![gp](https://cloud.githubusercontent.com/assets/1658215/16224350/fafcaa2e-37a1-11e6-9253-e8886ab9a21c.png)
Looks fine here.

Version 0.12.1 is[ on its way](https://build.opensuse.org/request/show/403801) into the devel project GNOME:Apps now.
From there it will go into Factory and eventually hit openSUSE Tumbleweed.

@zagortenay333 which version of openSUSE do you use?

**Comment by zagortenay333** [comment]
Oh, nice.

I'm on Tumbleweed

**Comment by zagortenay333** [comment]
Forgot to close this one.
