### ISSUE TITLE
Conflict with opensp

### ISSUE THREAD

**Issue by gui-don** [codito/gnome-pomodoro#229]
Hello,

Since latest release (0.12.1-1), I am not able to install `gnome-pomodoro` neither with AUR nor with makepkg (so now, you know this is on Archlinux).

The `jade` dependency is in conflict with `opensp`, which I need for other software.

Is there a solution or am I doomed?

Thanks!

**Comment by kamilprusko** [comment]
Hi,

You could remove docbook stuff from dependencies. Docbook is used to build a manpage. 

Please report packaging issues to [AUR](https://aur.archlinux.org/packages/gnome-shell-pomodoro/).

**Comment by gui-don** [comment]
Yep, it works. Thank you.

**Comment by kamilprusko** [comment]
```jade``` also causes dependency issues on Ubuntu 16.04. I expect it will affect other projects :(
