### ISSUE TITLE
Visual indicator if timer is paused with animations disabled

### ISSUE THREAD

**Issue by Isgar** [codito/gnome-pomodoro#230]
I love the new feature to pause the pomodoro timer. However, I cannot see if it is paused by looking at the icon and have to open the menu to verify the state.

I would suggest to put a simple pause icon (two parallel bars) inside the ring if it is paused.

**Comment by kamilprusko** [comment]
The indicator should be blinking when timer is paused. Doesn't it work for you?

I'm working on indicator for Unity and other desktops, and made it like you suggested - a small pause icon blinking over the regular indicator, but I don't think it as nice as in GNOME Shell.

**Comment by Isgar** [comment]
It is not blinking, it looks exactly the same as if it were running.

I am using Arch Linux with Gnome 20

**Comment by kamilprusko** [comment]
Works for me on GNOME 3.20 :/

Are you perhaps using a custom theme? Does restart of gnome-shell help (Alt + F2, then enter "r") ?

**Comment by Isgar** [comment]
I found the problem: I disabled animations in the tweak tools. I like it, however I do not want to enable animations in Gnome Shell.

It would be nice to see that it is paused in a static way.

**Comment by kamilprusko** [comment]
Yep, with animations disabled indicator is useless :-) I'll look into this.

Thanks!

**Comment by kamilprusko** [comment]
Patch will be included in 0.12.2 release, in a week or two.
