### ISSUE TITLE
Confusing styling on start icon

### ISSUE THREAD

**Issue by smichel17** [codito/gnome-pomodoro#235]
A picture tells a thousand words, so I'll just leave this, green being start button styling I would suggest.

![pomodoro_menu](https://cloud.githubusercontent.com/assets/6563664/18017323/ec6e3fb4-6b9e-11e6-92d8-819b788fa763.png)

![system_menu](https://cloud.githubusercontent.com/assets/6563664/18017325/eec7931e-6b9e-11e6-90bd-110594222b12.png)

**Comment by kamilprusko** [comment]
Thanks for suggestion.

It was my initial thought to add some outline, but it's tricky to make it work well with other themes.

**Comment by smichel17** [comment]
Having never used a non-default theme, what do the system menu buttons look like in that case? Can you just borrow their styling for all themes?

**Comment by kamilprusko** [comment]
My bad, it's already borrowed.

Css class responsible for system buttons is ```system-menu-action``` which is not generic. To make buttons smaller Pomodoro sets fixed ```padding``` and ```border```. Default theme actually changes *both* during hover.

Border could be set to 1px but this may not work well with themes that for instance don't define ```border-color``` or don't use border around these buttons.

**Comment by smichel17** [comment]
If there's not a great way to style the button with css, could you look into using a different icon? For example, a circle with an arrow-shaped transparency?

**Comment by kamilprusko** [comment]
I would rather keep the look, but extend the hit area to the "Pomodoro Timer" label, so that icon would be highlighted more easily / easier to hit. It may feel odd as there is no similar element in GNOME Shell, but I could give it a try.
