### ISSUE TITLE
Compatibility with gnome-shell 3.21.x/3.22?

### ISSUE THREAD

**Issue by aerostitch** [codito/gnome-pomodoro#236]
Hi @kamilprusko ,

Gnome-shell 3.21.91 arrived in the unstable repo of Debian.
I see that even in the latest version, your metadata.json.in doesn't claim compatibility with gnome-shell 3.21.x/3.22.
Do you have known incompatibilities with these versions of gnome-shell?

Thanks
Joseph

**Comment by kamilprusko** [comment]
Hi @aerostitch ,

I haven't checked 3.22 yet, will check during this week. Extension version checking in GNOME Shell will now be disabled by default (https://bugzilla.gnome.org/show_bug.cgi?id=770887), so after review I would bump straight to 3.22.

**Comment by aerostitch** [comment]
Thanks! :)

**Comment by zapashcanon** [comment]
Since [this commit](https://git.gnome.org/browse/gnome-shell/commit/?id=5e0e3e), released as a part of 3.21.92:

> Nowadays, the user interface has mostly stabilized with most changes happening under the hood. As a result, extensions written for previous versions of GNOME Shell are very much expected to keep working on updates, if it wasn't for the version check that requires a version bump in the extension metadata. There has been a setting to disable that check for a while, but it's existence isn't widely known (hence the common perception that "everything breaks on updates"). While there is still some risk that an out-of-date extension can be enabled without error, but fails spectacularly later (where we cannot catch the exception), it is reasonably small by now when compared to the ~95% of extensions that can be "unbroken", so swap the default value to disable version checks by default.

So, there's no need to update the `metadata.json` anymore. :)

**Comment by kamilprusko** [comment]
OK, Works just like in 3.20.

@aerostitch: I bumped the version in metadata.json and released it as [0.12.3](https://github.com/codito/gnome-pomodoro/blob/gnome-3.22/NEWS).

Best,
Kamil

**Comment by aerostitch** [comment]
Thanks!
Seems gnome 3.21+ don't care about the versions in metadata.json anymore, so you will probably end up removing it at some point.

**Comment by kamilprusko** [comment]
Extensions sort of monkey-patch GNOME Shell. There is no stable API, so I don't think versioning would go away.

There are expected brakeges in GTK+ with introduction of [GSK](https://media.ccc.de/v/16-gtk_are_we_in_the_future_yet) though :) (excuse my sarcasm, I love upcoming changes in gtk)

**Comment by aerostitch** [comment]
Hahahaha! Very true!:)
