### ISSUE TITLE
How to start it ?

### ISSUE THREAD

**Issue by Gameranand** [codito/gnome-pomodoro#237]
I just installed the program and it came under Accessories in Start Menu and when I open it it shows me preferences. Thats all good but how do I start the timer and make it show on my panel. Can't find any options there. I also checked if a new applet has been added to the list but no, there was none.

So how do I make it work ? Am I missing something here ?

**Comment by kamilprusko** [comment]
What desktop do you use?

If Unity, XFCE or Mate, check if you have version 0.12.2. If not, quit current app (Ctrl + Q from preferences window) and install package from http://gnomepomodoro.org... Support for appindicator landed just in last release.

**Comment by Gameranand** [comment]
I am currently using Cinnamon. Linux Mint LMDE2.

**Comment by kamilprusko** [comment]
I'm not sure whether Cinamon have support for appindicators out of the box, found extension for this
https://github.com/lestcape/Appindicator

But you can use it without indicator if you have gnome-pomodoro 0.12.0 or newer, it's now a default window instead of preferences

![gnome-pomodoro-window](https://cloud.githubusercontent.com/assets/1135423/18608004/4bc3b648-7cdd-11e6-8c27-ed19d66a37d4.png)

**Comment by stefan-kern** [comment]
i've tried installing this a few times over the past months now, but i can never get the indicator to show on ubuntu 16.04. i tried compiling it myself and downloading the 16.04 .deb (0.12.2-1_amd64) from the website. i tried killing the task from the task manager and restarting (some people mentioned that helps) but it just wont show up. is the indicator not working on gnome 3.18?

**Comment by kamilprusko** [comment]
@stefan-kern : I've tested it on 16.04, should work...

Can you provide output of?

    $ echo $XDG_CURRENT_DESKTOP
    $ gnome-pomodoro --quit
    $ G_MESSAGES_DEBUG="all" gnome-pomodoro

Which desktop do you use?

**Comment by stefan-kern** [comment]
Knowing that it can work I gave it another try. Ive looked into it with synaptic. Uninstalled all the previous versions and then installed gnome-pomodoro-shell and some other plugins that showed up when searching for pomodoro. Works fine now. Thanks for your help.

**Comment by kamilprusko** [comment]
Great! Thanks for info :)

**Comment by Tyrannogina** [comment]
Hi! I have the same issue, when I open it it only shows preferences. I am on Ubuntu 16.04 LTS, the current desktop ($echo $DESKTOP_SESSION) is 'ubuntu', so I understand gnome.
echo $XDG_CURRENT_DESKTOP -> Unity
gnome-pomodoro quit -> Could not parse arguments: Unknown option --quit
Run 'gnome-pomodoro --help' to see a full list of available command line options.
G_MESSAGES_DEBUG="all" gnome-pomodoro -> does not return anything

I tried installing with the gnome-pomodoro-shell command, from the .deb and through the Ubuntu Software thing, but nothing works, it just opens the preferences. At least with Ubuntu Software it displayed the app icon, with the others it was just command line. I also installed synaptic and try the 3 packages from there.

Any insights?

**Comment by marccarre** [comment]
Same issue, see below.
Is this application still maintained?

```console
$ echo $XDG_CURRENT_DESKTOP
Unity
$ gnome-pomodoro --quit
$ G_MESSAGES_DEBUG="all" gnome-pomodoro

** (gnome-pomodoro:29026): CRITICAL **: pomodoro_timer_get_state_duration: assertion 'self != NULL' failed

** (gnome-pomodoro:29026): CRITICAL **: pomodoro_timer_get_state: assertion 'self != NULL' failed

** (gnome-pomodoro:29026): CRITICAL **: pomodoro_timer_get_state_duration: assertion 'self != NULL' failed

** (gnome-pomodoro:29026): CRITICAL **: pomodoro_timer_get_state_duration: assertion 'self != NULL' failed

** (gnome-pomodoro:29026): CRITICAL **: pomodoro_timer_get_state: assertion 'self != NULL' failed

** (gnome-pomodoro:29026): CRITICAL **: pomodoro_timer_get_state_duration: assertion 'self != NULL' failed

** (gnome-pomodoro:29026): CRITICAL **: pomodoro_timer_get_state_duration: assertion 'self != NULL' failed

** (gnome-pomodoro:29026): CRITICAL **: pomodoro_timer_get_state: assertion 'self != NULL' failed

** (gnome-pomodoro:29026): CRITICAL **: pomodoro_timer_get_state_duration: assertion 'self != NULL' failed
```
The above command shows the Preferences window, but nothing else.
When closing the Preferences, the Pomodoro countdown does NOT appear.

```console
$ gnome-pomodoro --version
Pomodoro 0.12.2
$ apt-cache madison gnome-pomodoro
gnome-pomodoro |   0.12.2-1 | http://download.opensuse.org/repositories/home:/kamilprusko/xUbuntu_16.04  Packages
$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
$ uname -a
Linux sebulba 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Installation steps I followed were from http://gnomepomodoro.org/#download:

```console
$ curl -L https://download.opensuse.org/repositories/home:/kamilprusko/xUbuntu_16.04/Release.key | sudo apt-key add -
$ sudo sh -c "echo 'deb https://download.opensuse.org/repositories/home:/kamilprusko/xUbuntu_16.04/ /' >> /etc/apt/sources.list.d/gnome-pomodoro.list"
$ sudo apt-get update
$ sudo apt-get install gnome-pomodoro
```

Note that I eventually had to change `deb https://` into `deb http://` because I also experienced #333.

**Comment by JeGoi** [comment]
@marccarre Did your try to install it directly from this deb: https://download.opensuse.org/repositories/home:/kamilprusko/xUbuntu_16.04/amd64/gnome-pomodoro_0.12.2-1_amd64.deb
It has working for me.

**Comment by calocedrus** [comment]
@kamilprusko I have had the same issues as that reported in this thread, only the preference window opens. Attempts to use the keyboard shortcut/binding, modifying it to some other bindings was to no avail. Installation following @marccarre as well as via 
`sudo apt-get install gnome-shell-pomodoro`
, none gave me the timer window.
@JeGoi it didn't work with the following first-time-seen message (ubuntu 16.04, unity):

![image](https://user-images.githubusercontent.com/7334866/49051548-50500a00-f223-11e8-998a-e115706698a4.png)
