### ISSUE TITLE
(Translating) Error while generating pot file

### ISSUE THREAD

**Issue by etuardu** [codito/gnome-pomodoro#239]
Hi, I'd like to contribute to gnome-pomodoro providing translations, but I am not able to generate the pot file following the steps described at https://github.com/codito/gnome-pomodoro/wiki/Translating

While doing that I'm receiving the following error message:

```
gnome-pomodoro/po$ intltool-update --pot
can't open ./../data/org.gnome.pomodoro.gschema.xml.in: No such file or directory at /usr/bin/intltool-extract line 212.
xgettext: errore durante l'apertura di "../data/org.gnome.pomodoro.gschema.xml.in.h" in lettura: File o directory non esistente
ERROR: xgettext failed to generate PO template file. Please consult
       error message above if there is any.
```

**Comment by kamilprusko** [comment]
Hi @etuardu,

I recently switched pomodoro from intltool to pure gettext and obviously did not check it properly. Sorry for that...

I'll update the instructions and let you know once its ready to translate.

Thanks!

**Comment by kamilprusko** [comment]
I've updated the instructions and fixed the issues.

You're ready to go :)
