### ISSUE TITLE
Gettext version

### ISSUE THREAD

**Issue by ok2cqr** [codito/gnome-pomodoro#241]
It's really needed minimal version of gettext 0.19.8? In Ubuntu 16.04 there is version 0.19.7. I tried to modify the version in configure.ac, but compilation fails with this message:

make[3]: Leaving directory '/home/prace/tmp/gnome-pomodoro/data'
make[2]: Leaving directory '/home/prace/tmp/gnome-pomodoro/data'
Making all in po
make[2]: Entering directory '/home/prace/tmp/gnome-pomodoro/po'
make[2]: *** No rule to make target 'Makevars', needed by 'Makefile'.  Stop.
make[2]: Leaving directory '/home/prace/tmp/gnome-pomodoro/po'
Makefile:498: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/prace/tmp/gnome-pomodoro'
Makefile:430: recipe for target 'all' failed
make: *** [all] Error 2

I'm trying to update Czech translation but it seems there are no all strings used in program available to translate...

**Comment by kamilprusko** [comment]
Looking at [release notes](https://lists.gnu.org/archive/html/info-gnu/2016-06/msg00003.html), 1.19.7 should do.

**Comment by ok2cqr** [comment]
Thanks! Now I have no idea why I got the error :(.

**Comment by kamilprusko** [comment]
po/Makevars file should be added to git repo.

I need to follow a [migration guide](https://wiki.gnome.org/MigratingFromIntltoolToGettext) again and make patches.

**Comment by kamilprusko** [comment]
Done.

I included .pot file in the repo (not sure I should do that), but for reference it's now done by

    make -C po gnome-pomodoro.pot-update

to update .po file

    cd po
    msgmerge --output-file=cs.po cs.po gnome-pomodoro.pot

**Comment by ok2cqr** [comment]
Thank you! I'll translate the rest of the strings and create pull request.
