### ISSUE TITLE
Idea - run command before break and after break

### ISSUE THREAD

**Issue by krchat** [codito/gnome-pomodoro#246]
I'd like to sleep screen and start music files before break time and wake up screen after break time
So, what about add user commands before and after running break time?

**Comment by kamilprusko** [comment]
It's done in master branch #70, will be in next release.

**Comment by krchat** [comment]
thanks,  Kamil, may I contact with you to discuss about another Gnome program - Scheduled task.
I compiled it and set, but It doesn't work. I'm a newbie in Linux, so I'll appreciate you if you give me your assistance. But after your next release, I suppose all functions will be in your program too. Now I try to use gnome-schedule to extend possibilities your brilliant pomodoro.
