### ISSUE TITLE
[ux] Don't always resume the pomodoro after reboot

### ISSUE THREAD

**Issue by smichel17** [codito/gnome-pomodoro#249]
Steps to reproduce:

- Start the timer
- Do work for a while
- Turn off your computer
- Go to sleep for the night
- Wake up in the morning
- Start your computer

Expected result: Timer is stopped
Actual result: Pomodoro starts immediately

---

I like the behavior where the pomodoro resumes on reboot, but if it's been a sufficiently long time (maybe 1 hour? 2 hours?) I'd like it to be stopped on boot.

**Comment by kamilprusko** [comment]
Thanks @smichel17

I've actually fixed it in 9ccb748a1e08bea3feff6335280ec3715f13d28f in master branch. Timer will be reset if restored after more than 1h... also during shutdown timer won't behave as if it's running in background, but rather as if paused.

By not restoring paused state you get a notification from Pomodoro... it's done on purpose :) But I see your point. I'm not sure what would be best behavior here.

**Comment by smichel17** [comment]
Ack, I said "paused" where I meant "stopped".

**Comment by kamilprusko** [comment]
Closing. It has been fixed/improved.
