### ISSUE TITLE
application doesn't pass to next timer session

### ISSUE THREAD

**Issue by krchat** [codito/gnome-pomodoro#250]
This is a nice program. Thanks for it. But unfortunately I have a little problem. In my case, when the first pomodoro and a break passed, the next pomodoro doesn't start automatically, but it's in pause mode.
I don't know how to set it in automatic cycle mode.

**Comment by smichel17** [comment]
It should start automatically after a break... If you have the setting `Wait for activity after a break` turned on, then it will wait for you to wiggle the mouse or type something to start.

**Comment by krchat** [comment]
I don't know anything about this setting: "Wait for activity after a break" - Where can I check this setting?

**Comment by kamilprusko** [comment]
> In my case, when the first pomodoro and a break passed, the next pomodoro doesn't start automatically, but it's in pause mode.

It's a bug. "Wait for activity after a break" setting is hidden on other desktops then GNOME. However Pomodoro still relies on libgnome-desktop to detect activity and pauses the timer after a break.

For now you could disable it using dconf, it's "pause-when-idle" setting in org.gnome.pomodoro.preferences.

I made a fix 0a228fbec84d558d1f1d6d69dd562947aec04064 to not pause the timer but haven't tested yet. Implementing it for other desktops would likely be X11, mir and wayland-specific, and in some cases (GNOME) desktop-specific...

**Comment by smichel17** [comment]
![pomodoro](https://cloud.githubusercontent.com/assets/6563664/20804121/aa84e4dc-b7bf-11e6-94e6-3ae38c85b351.png)

**Comment by krchat** [comment]
Thanks, yes, it's only on gnome not even gnome classic. I change this option and timers work OK.
