### ISSUE TITLE
Support for Fedora 25

### ISSUE THREAD

**Issue by psukys** [codito/gnome-pomodoro#253]
Hello,

currently installing through extensions.gnome.org for Fedora 25 (Gnome 3.22.2) does not work, would be cool to have it running on newest version of Fedora.

**Comment by kamilprusko** [comment]
Hi,

You can install from official repos, package ```gnome-shell-extension-pomodoro```, or from source. You'll need to uninstall your old extension.

Distributing pomodoro back through extensions.gnome.org would be tricky, because it needs a binary distribution (it's written in Vala), has a DBus service and plugins... overall it's easier to install pomodoro system-wide.

I could put the extension back, but require to install gnome-pomodoro package... but that has it's own issues, what if the app and extension becomes incompatible?

I should make it available through flatpak.

**Comment by psukys** [comment]
Thank you! I failed to find some documentation on current official packages, is there one. If not, maybe it would be a good idea to use one?

**Comment by smichel17** [comment]
Is this not what you are looking for? http://gnomepomodoro.org/#download

**Comment by psukys** [comment]
Thanks @smichel17, forgot to check the website, was only looking through folders for markdown files and the github wiki :)

**Comment by 183amir** [comment]
@kamilprusko if you distribute your app through flatpak, you cannot distribute the gnome shell extension through flatpak as far as I know. So users would have to install through flatpak and then install the extension from extensions.gnome.org.

your app is great btw.

**Comment by kamilprusko** [comment]
@183amir Can be done, just requires permissions to access the file system. I already use it for development.

**Comment by kamilprusko** [comment]
Other apps using plugins system need filesystem permissions too, I don't think it's a big deal when compared to .debs, .rpms... or apps on Android.

I haven't figured out how to distribute with flatpak. To run Pomodoro, extract json file and run

[org.gnome.Pomodoro.zip](https://github.com/codito/gnome-pomodoro/files/697017/org.gnome.Pomodoro.zip)

    $ flatpak-builder --force-clean --ccache --require-changes app org.gnome.Pomodoro.json
    $ flatpak-builder --run app org.gnome.Pomodoro.json gnome-pomodoro

**Comment by 183amir** [comment]
I don't see any gnome shell extension **exported** in your flatpak'ed app. Am I missing something here?
I mean when I run the application using flatpak, I don't see any gnome shell extension added.

**Comment by kamilprusko** [comment]
@183amir You're right.

**Comment by 183amir** [comment]
I reported an issue here: https://github.com/flatpak/flatpak/issues/481 and asked if it is possible to do so.

**Comment by kamilprusko** [comment]
@183amir Thanks for your help.

I suppose I could fork my own project, drop support for other desktops, rewrite it to Python and distribute Pomodoro through extensions.gnome.org back again. Seriously :)

Or let Pomodoro request GNOME Shell to install the extension from extensions.gnome.org and hope there are no compatibility issues.

I'm closing this issue as support for Fedora 25 is ok now.
