### ISSUE TITLE
Run custom command on Pomodoro start/end

### ISSUE THREAD

**Issue by Thor77** [codito/gnome-pomodoro#257]
I would like to have the ability to run a custom command on Pomodoro/break start/end.
This would add some nice opportunities:
* Easily solve #245 
* Pause/Play music during breaks
* Start specific programs when starting a Pomodoro/quit them for breaks
[...]

**Comment by Thor77** [comment]
Argh, should've searched the issue tracker more precisely, already tracked and solved by #70

**Comment by kamilprusko** [comment]
Yep, it's done in master branch. It will be in 0.13 version which I hope to release this month.

Testing / suggestions are welcome.
