### ISSUE TITLE
i3 and "wait for activity after break"

### ISSUE THREAD

**Issue by BonarBeavis** [codito/gnome-pomodoro#260]
Hello,

the "wait for activity after break" does not work with i3. With the new actions-feature I wrote a little dirty workaround. 
```
#! /bin/bash
xinput test 9 | while read in ; do
  break
done
gnome-pomodoro --resume
```

`xinput list` show possible devices.

Cheers

**Comment by kamilprusko** [comment]
Hi,

It won't be needed with gnome-pomodoro 0.13.0, if you can upgrade. This feature still is not avaliable outside GNOME Shell.

It could be made for X11 by reading last event time. On some desktops last event time is avaliable through ScreenSaver DBus interface, but that's not too reliable... If there was a way to make it for wayland / or libinput then I would make it for X11 too.

**Comment by BonarBeavis** [comment]
Hi,

sorry I was not very clear, when this script is triggered like this:

![image](https://cloud.githubusercontent.com/assets/3330855/21751377/73863c36-d5c6-11e6-9962-16011dafab83.png)

It resumes pomodoro after a break with any keypress. So it is not needed to manually resume the pmodoro, what is easy forgotten.
