### ISSUE TITLE
No icon visible in notification area on Ubuntu 16.04.1 with Unity 7.4.0

### ISSUE THREAD

**Issue by wkmanire** [codito/gnome-pomodoro#263]
I'm using Ubuntu 16.04.1 LTS with Unity 7.4.0.

I installed gnome-pomodoro-shell (Version: 0.11.0-2build1) from the Ubuntu Software center and launched it.

I expected to see the Pomodoro icon in the top bar.

Instead, when I launch it, I only see the configuration window and when I close it the application exits. There doesn't seem to be any way to actually use gnome-pomodoro.

---

I believe that at one time it was possible to use gnome-pomodoro in Unity but no longer. Many users of Ubuntu 16.04 with the default DE of Unity are leaving bad reviews in the Ubuntu Software app as you can see in the screenshot below.

Do you intend to support Unity? What is required to get this working in Unity under Ubuntu 16.04 LTS? Are you looking for a contributor to help fix this?

![screenshot from 2017-01-18 15-52-32](https://cloud.githubusercontent.com/assets/217010/22088036/38471d0c-dd96-11e6-9c38-37222ab8ce29.png)

**Comment by kamilprusko** [comment]
I just have no idea how to upload newer version to Ubuntu repos for 16.04. It should be fine in 16.10.
