### ISSUE TITLE
App doesn't open

### ISSUE THREAD

**Issue by mahdiG** [codito/gnome-pomodoro#267]
Hi. I'm on debian testing and I installed the app via debian repo. When I enter the command 'gnome-pomodoro' it says:
ERROR:gnome.c:315:gnome_extension_state_to_string: code should not be reached
Aborted
But opening it as root works fine.

**Comment by aerostitch** [comment]
Hi,
Did you try by enabling it via gnome tweak tools?
Thanks
Joseph

**Comment by mahdiG** [comment]
Well it didn't appear there in tweak tools but after a reboot everything works fine. Thanks :)
