### ISSUE TITLE
The sliders for durations only move to the extremes

### ISSUE THREAD

**Issue by jokuNimi** [codito/gnome-pomodoro#268]
When I try to drag the slider, it only goes to 1 minute or 2 hours. Using the arrow keys doesn't work either.

I have installed gnome-pomodoro through aur on arch linux (pomodoro version 0.13.0), and am running gnome version 3.22.2. I have tried changing my gtk theme. The brightness and sound volume sliders in gnome shell work.

**Comment by jokuNimi** [comment]
Changing the settings with gsettings (either from terminal or with dconf-editor) works.

**Comment by kamilprusko** [comment]
Might be a bug in Gtk+, I'll try it under a newer version.

I traded steppers (keys / mouse scroll) for having a logarithmic scale.

**Comment by kamilprusko** [comment]
Fixed in 11427e560e78344d514a02fe4da9ab40fb00cdbb
