### ISSUE TITLE
doubled notifications on Fedora 25

### ISSUE THREAD

**Issue by mvhirsch** [codito/gnome-pomodoro#277]
Hi,

I recently installed a fresh version of Fedora 25 (removed Fedora 23 and freshly installed 25) and afterwards I installed one of my favorite tools: gnome-pomodoro.

It works like a charm but I noticed that every notification from it (announcing a break, a new pomodoro, a long break, ...) will be doubled. 

![screenshot from 2017-02-28 09-10-05](https://cloud.githubusercontent.com/assets/573047/23396783/bf94d5a0-fd95-11e6-8531-63e93fe96406.png)

I can't see anything in logs, but this (also doubled):

> Feb 28 09:04:20 aurora gnome-pomodoro[3077]: Trying to remove a child that doesn't believe we're it's parent.
> Feb 28 09:04:20 aurora gnome-pomodoro[3077]: Trying to remove a child that doesn't believe we're it's parent.

I installed it via dnf, current installed version is 0.13.0-2.fc25.

**Comment by kamilprusko** [comment]
Fixed in 0.13.1

@mbooth101 submitted it to Fedora repos. For Fedora 25 it's currently in testing
https://apps.fedoraproject.org/packages/gnome-shell-extension-pomodoro/

**Comment by mvhirsch** [comment]
@kamilprusko @mbooth101 The fix works as expected, thank you very much!

For everyone else waiting for the stable update in Fedora update repository, here is how I installed it from the testing repos:

`$> dnf update gnome-shell-extension-pomodoro --enablerepo=updates-testing`
