### ISSUE TITLE
unable to changes times preferences: cursors duration stuck to 1mn or 2 hours 

### ISSUE THREAD

**Issue by Asenar** [codito/gnome-pomodoro#283]
Hi,

The default values for the 3 cursors are 25 minutes for a pomodoro, 5 minutes for short break and 15 minutes for long break.

But if I try to change theses values (by mouse or keyboard), the cursors moves to the only 2 extremes left and right positions, making it correspond to 1 minute, or 2 hours.

I have been able to restore theses values in `dconf-editor`

I'm using debian testing and i3wm, but most of gnome applets are working fine (nm-applet or hamster for example)

**Comment by smichel17** [comment]
It's fixed in the next release. See #268.

**Comment by Asenar** [comment]
Thanks you :)
