### ISSUE TITLE
Extensionless mode

### ISSUE THREAD

**Issue by smithfred** [codito/gnome-pomodoro#288]
At the moment under GNOME, the shell extension is enabled every time gnome-pomodoro is launched as an application.

It should be at least possible for gnome-pomodoro to operate as a standalone application if only standard notifications are used (not sure about fullscreen) and for the application to not persist in the background if its window is closed; can a mode like this be provided (as a pref ideally so that overriding the application's .desktop file isn't required)?

**Comment by kamilprusko** [comment]
> for the application to not persist in the background if its window is closed
In more recent versions if you choose "Quit" from the indicator, or the app menu or hit ```Ctrl + Q``` in any window it will disable both the app and the extension.

> Extensionless mode
Not gonna happen. It's usable without the extension (you can temporarily disable the extension via Tweak Tool to try it), but the extension gives polish that we can't achieve using GTK+ and default notifications APIs.

> if only standard notifications are used
Currently, the extension provides more polished notifications (there's a fallback), the indicator, hotkey, support for GNOME Shell's do-not-disturb mode and reminders. For future releases, I would love to have a better integration with the Lock Screen.

**Comment by smithfred** [comment]
That's unfortunate. A standard app and standard notifications would actually be nice as a less up-front/enforced mode, for those users who prefer that approach, and I would think it wouldn't take that much to support that. That said, I could be wrong about the work involved, and I don't have a say in the end ;)
