### ISSUE TITLE
Slider has only 2 options

### ISSUE THREAD

**Issue by smarlowucf** [codito/gnome-pomodoro#289]
Attempt at setting the duration options via sliders provides only two options.
 - 1 min
 - 2 hrs

There's no way to set an intermediate value. Also, could not find a config file to manually modify.

System:
- openSUSE Tumbleweed
- GNOME Shell 3.24.0

**Comment by kamilprusko** [comment]
It's fixed in the next release (#268).

Package for openSUSE has been submitted
https://build.opensuse.org/package/revisions/GNOME:Apps/gnome-pomodoro

**Comment by smarlowucf** [comment]
Thanks @kamilprusko !
