### ISSUE TITLE
not start: type error keybinding is undefined

### ISSUE THREAD

**Issue by trinkity** [codito/gnome-pomodoro#290]
Install from browser gnome extension: not work.
compile from git: last version - not work
debug:
Shell-Message: Extension "pomodoro@arun.codito.in" had error: TypeError: Shell.KeyBindingMode is undefined

----
EDIT
Work with this command:
sudo apt-get install gnome-shell-pomodoro
after... reboot
---
bye

**Comment by kamilprusko** [comment]
KeyBindingMode was replaced with ActionMode in gnome-shell in 3.16. The code from master branch requires GTK+ 3.20 among other dependencies.

Most comprehensive info on how to install gnome-pomodoro is at http://gnomepomodoro.org/
