### ISSUE TITLE
Autostart program in hide mode just in notification area

### ISSUE THREAD

**Issue by krchat** [codito/gnome-pomodoro#292]
I'd like the program may start auto with loading OS, but If I use StartUp application to add this program, it starts in its full size window. 
How make it start in hide mode, just with shortcut in notification area?

**Comment by kamilprusko** [comment]
You can add ```--no-default-window``` while specifying the startup app

    gnome-pomodoro --no-default-window

Same goes if you would like to add a keyboard shortcut

    gnome-pomodoro --no-default-window --start-stop

It was reported in #252
