### ISSUE TITLE
not installing fedora 25 on April 19 

### ISSUE THREAD

**Issue by codelovesme** [codito/gnome-pomodoro#294]
I am not able to install the extension. I am getting this error below.
[Screenshot](http://imgur.com/gR9lJ2L)

**Comment by kamilprusko** [comment]
Are you trying to install Fedora 24 .rpm on Fedora 25?

Download instructions for Fedora are up to date - there are no local packages from OBS yet (no OBS support) :( But you can install Pomodoro from official repos

    $ sudo dnf install gnome-shell-extension-pomodoro

**Comment by jflory7** [comment]
Fedora 25 went end-of-life [on December 12, 2017](https://fedoramagazine.org/fedora-25-end-life/). I might suggest closing this issue in favor of testing on a newer version of Fedora (I am using the extension on Fedora 27 without issue).
