### ISSUE TITLE
Problem with "Hide other notifications"

### ISSUE THREAD

**Issue by FGuemard** [codito/gnome-pomodoro#297]
This feature was working properly with the package gnome-shell-pomodoro but after installing gnome-pomodoro the notifications always appear during a pomodoro.

Any ideas about this problem ?

**Comment by kamilprusko** [comment]
Haven't noticed that... Thanks for the report.

Perhaps it's more related to GNOME Shell version... they dropped this feature from the UI but still worked through API. I suspect it stopped working in 3.22. I'll see what I can do.

**Comment by kamilprusko** [comment]
Fixed in 0cab45ff47d7bf9b4e6321afbbe43f7d8e881e05 (in gnome-3.22 branch)

**Comment by kamilprusko** [comment]
Fix released in 0.13.2

**Comment by FGuemard** [comment]
Thanks for the work !

When do you purpose the update on the openSUSE Build Service ?

**Comment by kamilprusko** [comment]
> When do you purpose the update on the openSUSE Build Service ?

Just updated, https://build.opensuse.org/package/show/home:kamilprusko/gnome-pomodoro

**Comment by FGuemard** [comment]
Thanks ! I've updated the package and it works fine !
