### ISSUE TITLE
shadow of countdown does not change

### ISSUE THREAD

**Issue by twhitbeck** [codito/gnome-pomodoro#306]
I almost think I'm seeing things, but I'm pretty sure the text-shadow on the countdown does not change when the numbers change.

For example, my short break is 2:00, and when it starts and the screen overlay with the countdown starts counting down, I faintly see the drop shadow on the text remain `2:00` as the counter changes.

**Comment by kamilprusko** [comment]
It's a long standing bug and I'm not sure what's the cause, at times it works fine...

In master branch, I've already removed the shadow in favor of a blur shader, if supported.

![screenshot from 2017-08-08 20-18-38](https://user-images.githubusercontent.com/1135423/29087676-f1c04f0e-7c76-11e7-9f6a-103186aca1cd.png)

Works smooth enough on integrated graphics, but may be little choppy on 4K / dual monitors though.

**Comment by twhitbeck** [comment]
that's one way to get around it
I like the blur

**Comment by twhitbeck** [comment]
If you're moving away from the drop shadow, I'm fine closing this issue.
