### ISSUE TITLE
Compatibility with gnome-shell 3.25+

### ISSUE THREAD

**Issue by aerostitch** [codito/gnome-pomodoro#308]
Hi @kamilprusko ,

Hope you're doing fine.
In Debian we started shipping gnome 3.25+. the metadata.json.in limits the usability of the plugin to 3.24 max. Do you see any issue raising that at leasxt to 3.26?

Debian bug reference: https://bugs.debian.org/874286

Thanks
Joseph

**Comment by kamilprusko** [comment]
Hi Joseph

Seems to work fine on 3.26. There were no breaking changes in GNOME Shell for us in this release. There are new warnings which I haven't fixed yet.

So I've tagged a 0.13.3 release, with:

* Support for GNOME Shell 3.26
* Added Dutch translation
* Added Swedish translation

Best,
Kamil

**Comment by aerostitch** [comment]
Perfect, thanks a lot! :)
