### ISSUE TITLE
Segmentation faults when clicking notifyd buttons

### ISSUE THREAD

**Issue by Elm7** [codito/gnome-pomodoro#311]
Hello, thanks alot for the app.
Clicking notification popup buttons causes a segmentation fault (debian 9 with XFCE, 0.13.3).

**Comment by Elm7** [comment]
ok, I understand now better how the app motifications is passed to the notifyd one and thoigh a bit non obvious I can use that.

So remains the segmentation faults.

**Comment by kamilprusko** [comment]
The app was designed with some notifications in mind. Removing notifications sounds like building a silent alarm clock, it just misses the point.

Segfault is notifyd issue. Actions are optional part of Freedesktop spec, notifyd could just disable them. There's nothing to be done on Pomodoro side - we use [Gio notification API](https://developer.gnome.org/gio/stable/GNotification.html) and it works well with GNOME Shell notification daemon including actions, no segfaults. Actions also used to work in Unity (haven't checked that in a while), notification daemon there just opened a Gtk dialog window with actions as buttons... it was horrible.

Proposals in #298 are meant for GNOME Shell. It's not possible to implement most of them with notifyd.

**Comment by Elm7** [comment]
Thank you for the clarification about the segfault.

> The app was designed with some notifications in mind. Removing notifications sounds like building a silent alarm clock, it just misses the point.

I was just thinking of using only the app resident dimed fullscreen "notifications" with the timer which I like provided they are more stable (do not disappear on keystroke or mouse movment) and not at all the notifyd ones. That would be a good solution to me. But that was just an idea.

**Comment by kamilprusko** [comment]
Sure, I appreciate feedback! :)

I looked notifyd code https://github.com/xfce-mirror/xfce4-notifyd/tree/master/xfce4-notifyd and there seems to be an option to "mute" notifications of a particular app - might be for you.

Desktop notifications in notifyd are just poorly implemented, it's a broader problem than just for Pomodoro. If an app schedules a notification it gets displayed immediately and vanishes after a fixed time, regardless whether user is at the desk or not. In GNOME Shell its solved by IdleMonitor service so notifications are held back to ensure they are displayed to user.
