### ISSUE TITLE
Segfaults in 0.13.3

### ISSUE THREAD

**Issue by mbooth101** [codito/gnome-pomodoro#313]
Hi,

Since I updated the Fedora package to gnome-pomodoro 0.13.3, some users have reported segfaults.

Please see the backtraces attached to the following bugs:

* Fedora 27: https://bugzilla.redhat.com/show_bug.cgi?id=1499298
* Fedora 26: https://bugzilla.redhat.com/show_bug.cgi?id=1500988

Are either of these known to be fixed in the master branch?

**Comment by kamilprusko** [comment]
Hi @mbooth101 and thanks for reporting this :)

Both remain to be fixed.

The first segfault I believe may happen after adding gnome-pomodoro to autostart, when gnome-shell is not yet initialized or there is no notification daemon.

The second happens at application shudown. I've do not reproduce it with code from master branch, but I get related errors

    (gnome-pomodoro:2514): Gtk-CRITICAL **: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

I'll try to fix them. It may take me a month to wrap up 0.14 release; there are few more things to do and I couldn't find much time for Pomodoro lately :(

**Comment by mbooth101** [comment]
Either these segfaults stopped occuring because of a fix to gnome-pomodoro or a fix in something else I don't know, but I haven't seen a new segfault from Fedora users in a long time, closing.
