### ISSUE TITLE
Parameter to start break and long break from cli command

### ISSUE THREAD

**Issue by mgallego** [codito/gnome-pomodoro#315]
I'm using the command `gnome-pomodoro` with `--start` and `--stop` to integrate the application with emacs org-pomodoro, executing the command on org-pomodoro events.

I'm looking for a parameter to execute a **break** and **long break** in the application, but I can't found this parameters, and I don't know if exists.

ie. `gnome-pomodoro --start-break` or `gnome-pomodoro --start-long-break`

Exists any way to execute this actions with the command? 

Thank you.

**Comment by kamilprusko** [comment]
Thanks for feedback.

Yeah, it was meant for typical use cases only... You can use D-Bus interface directly - it's more powerful and perhaps more lightweight.

    $ dbus-send --session --type=method_call --dest='org.gnome.Pomodoro' /org/gnome/Pomodoro org.gnome.Pomodoro.Start
    $ dbus-send --session --type=method_call --dest='org.gnome.Pomodoro' /org/gnome/Pomodoro org.gnome.Pomodoro.Stop
    $ dbus-send --session --type=method_call --dest='org.gnome.Pomodoro' /org/gnome/Pomodoro org.gnome.Pomodoro.SetState string:"long-break" double:0
    $ dbus-send --session --type=method_call --dest='org.gnome.Pomodoro' /org/gnome/Pomodoro org.gnome.Pomodoro.SetState string:"short-break" double:0
    $ dbus-send --session --type=method_call --dest='org.gnome.Pomodoro' /org/gnome/Pomodoro org.gnome.Pomodoro.Skip

```SetState``` takes state name ('pomodoro', 'short-break', 'long-break', 'null') and a timestamp of the new state (0 for current timestamp).

For playing with D-Bus I recommend d-feet tool.

**Comment by mgallego** [comment]
Thank you very much.
