### ISSUE TITLE
Fails to minimize to Tray Area

### ISSUE THREAD

**Issue by seakros** [codito/gnome-pomodoro#324]
Dell XPS 13 / Antergos (Arch) / Gnome / TopIcon Plus Extension enabled for tray icons.

For some reason, on this computer, upon launching Pomdoro I get the following error:

Failed to enable extension
SyntaxError: Expected expression, got '<'

**Comment by kamilprusko** [comment]
Remove old extension from ```~/.local/share/gnome-shell/extensions/pomodoro@arun.codito.in```, you may use Tweak Tools or do it manually; then restart gnome-shell or logout.

**Comment by seakros** [comment]
Resolved - does this just mean there is a difference between where extensions are stored now and where they used to be?
