### ISSUE TITLE
Compilation fails on Fedora 27

### ISSUE THREAD

**Issue by etem** [codito/gnome-pomodoro#325]
Hello, 

I'm getting below error messages when trying to compile on Fedora 27

> configure.ac:19: installing './compile'
configure.ac:14: installing './missing'
lib/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
configure: loading site script /usr/share/config.site
./configure: line 2441: syntax error near unexpected token `git-directory'
./configure: line 2441: `AX_IS_RELEASE(git-directory)'

**Comment by kamilprusko** [comment]
Try installing ```autoconf-archive```. Full dependencies:

    $ sudo dnf install autoconf-archive gettext vala vala-tools pkg-config desktop-file-utils glib2-devel gtk3-devel libappstream-glib-devel libappindicator-gtk3-devel libcanberra-devel libpeas-devel gom-devel gobject-introspection-devel gsettings-desktop-schemas-devel gstreamer1-devel

Is it enough or there are more dependency issues?

**Comment by mbooth101** [comment]
Since gnome-pomodoro ships with Fedora 27, you should be able to simply do this:

    sudo dnf build-dep gnome-pomodoro

**Comment by mbooth101** [comment]
BTW, F27 is EOL and Fedora 28 will be soon too. I recommend closing this one too.

This is still the best way install the build dependencies for software that is shipped with all current versions of Fedora:

```
sudo dnf build-dep <package_name>
```
