### ISSUE TITLE
not able to run the app on elementary OS 0.4.1 Loki

### ISSUE THREAD

**Issue by banerjeesamrat** [codito/gnome-pomodoro#328]
I have installed the app from elementary appcenter and it is showing installed:

![screenshot from 2017-12-02 01 47 19](https://user-images.githubusercontent.com/31121849/33501540-f6d1a45c-d702-11e7-838b-f7fc8ee86b1c.png)

But I cannot find it on my system.

I tried another way by trying to run it through the terminal but it is only showing the preferences window and no option to start the app:

![screenshot from 2017-12-02 01 52 32](https://user-images.githubusercontent.com/31121849/33501695-7d65d394-d703-11e7-993a-b4c4b0bd4cdb.png)

I also tried downloading the app from http://gnomepomodoro.org/ but I had problems with the make step.

I really need the app to organize myself better so could someone please help me find the solution to this.

**Comment by kamilprusko** [comment]
0.11 had no timer window and appindicator was added in a point release - both are in 0.12. You may install .deb for Ubuntu 16.04 from http://gnomepomodoro.org/

You may also have a look at
  * Tomate https://github.com/eliostvs/tomate-gtk
  * Tomato https://quassy.github.io/elementary-apps/Tomato/
  * Pomodoro https://quassy.github.io/elementary-apps/Pomodoro/

Support for ElementaryOS needs more love. But with old packages and Juno beta not out yet it's a bit limiting.
https://github.com/codito/gnome-pomodoro/issues/276
