### ISSUE TITLE
Configuration Options?

### ISSUE THREAD

**Issue by ndmax** [codito/gnome-pomodoro#329]
I am using Pomodoro 0.13.4 installed on Ubuntu 17.10, running in a legacy Xorg session.

Maybe I'm missing something very obvious, but I simply cannot find any of the [available options](https://github.com/codito/gnome-pomodoro/wiki/Configuration) to manage the Pomodoro session.

Namely, I cannot seem to find any way to reset the session count; no matter now many times I completely exit the program, the timer picks up with the previous session count, resulting (after returning to work after an interrupted series) in a premature long break.

How can I restore interface access to the program's options, or modify the configuration manually?  I do not see (or correctly interpret) the reset option in dconf.

**Comment by kamilprusko** [comment]
It's been reported in #305

There is currently no such option. In master branch will reset after 1h if left disabled.
