### ISSUE TITLE
Stale TimerBanner causes gnome-shell crash

### ISSUE THREAD

**Issue by fortime** [codito/gnome-pomodoro#334]
Thanks for your great work.

With 0.14.0, the extension will cause crash of gnome-shell when notifications popup. After debuging, I found the crash happened at https://github.com/codito/gnome-pomodoro/blob/fe52244d43cc8fbd0c1752d51693501f3fb32f84/plugins/gnome/extension/notifications.js#L718

It seems like the `TimerBanner` doesn't release its resources. Then, I found `NotificationMessage` parent of `TimerBanner` receives signal *close* to release its resources. So I change https://github.com/codito/gnome-pomodoro/blob/fe52244d43cc8fbd0c1752d51693501f3fb32f84/plugins/gnome/extension/notifications.js#L659 signal *destroy* to *close*.
After that, crashes disappear.

BTW,  I think `PomodoroEndNotification` and `PomodoroAfterNotification` have the same problem. After banner had been destroyed, they haven't destory themself.

**Comment by kamilprusko** [comment]
Indeed, *destroy* signal is never emitted. Fixed in 06c6aa17005e31275b03bea853ae02975ed59c67

Notifications should be fine.

Thanks!
