### ISSUE TITLE
Text indicator-type and Dark Theme plugin not working

### ISSUE THREAD

**Issue by Spectator6** [codito/gnome-pomodoro#337]
Hello! 

Whenever I try to set the indicator-type to text, it remains as the default icon type. In command-line I am typing the following: 
`$ gsettings set org.gnome.pomodoro.plugins.gnome indicator-type text`

On a potentially related note, whenever I go into the Preferences -> Plugins and enable the app's Dark Theme, upon restart it remains the default "light" theme.

If it's of any use, I'm currently running Lubuntu, using the latest Ubuntu 17.10 distribution. Please let me know if you need any more info or if there's anything further I can test here on my end!

Your app is great, thank you for your help and support!

All the best,
-Blake

**Comment by kamilprusko** [comment]
Thanks for the report.

The ```org.gnome.pomodoro.plugins.gnome.indicator-type``` will work only in GNOME Shell. There is no way to add similar option with libappindicator.

Dark Theme sets a dark variant of the theme, but theme must support this. One such theme is Adwaita, and the change is instant.
