### ISSUE TITLE
Failing installation on Fedora 24

### ISSUE THREAD

**Issue by piotr-kubica** [codito/gnome-pomodoro#342]
Double click rpm 64 bit. Installer runs but does not finish.
Message displayed:

> Detailed errors from the package manager follow:
> 
> Could not depsolve transaction; 1 problem detected:
> 0. nothing provides libappindicator3.so.1()(64bit) needed by gnome-pomodoro-0.13.4-1.1.x86_64

**Comment by piotr-kubica** [comment]
`sudo dnf install libappindicator` 

output:

> Last metadata expiration check: 2:33:21 ago on Sat Feb 24 07:30:56 2018.
> Package libappindicator-12.10.0-11.fc24.x86_64 is already installed, skipping.
> Dependencies resolved.

**Comment by piotr-kubica** [comment]
Installation from repository works.

> sudo dnf install gnome-shell-extension-pomodoro

**Comment by jflory7** [comment]
For what it's worth, Fedora 24 went end-of-life [on August 8, 2017](https://fedoramagazine.org/fedora-24-eol/). I am using the timer on Fedora 27 and do not have the same issue described in the original comment.

I would suggest using the packaged version in the official repositories whenever possible.

**Comment by mbooth101** [comment]
In fact the oldest support Fedora right now is 27. It is impossible to push updates to packages in EOL versions of Fedora -- this issue can probably be closed :-)

**Comment by mbooth101** [comment]
@kamilprusko BTW feel free to tag me on Fedora related issues, since I am the de-facto maintainer of the pacakge in that distro :-)

**Comment by kamilprusko** [comment]
@mbooth101: will do. Thanks again! :)
