### ISSUE TITLE
Deprecation of libappindicator in Debian

### ISSUE THREAD

**Issue by aerostitch** [codito/gnome-pomodoro#353]
Hi @kamilprusko ,

Not sure if you've heard the news but libappindicator is being deprecated in Debian in favor of ayatana-indicators. See: http://bugs.debian.org/895037
Not sure if it's going to be the same for other distros but I guess so.
The source of the new one is https://github.com/AyatanaIndicators/libayatana-appindicator
It seems there are a few adjustments to do to support that.
Do you know if it's a lot of work to port it over?

Thanks
Joseph

**Comment by kamilprusko** [comment]
Hi @aerostitch 

Thanks for the info. I'll check whether it's adopted by upstream Mate and XFCE before replacing appindicator. Looks like it'll just need changes to configure.ac and Makefiles (https://github.com/mate-desktop/mate-polkit/pull/41/commits/8350ca2a4f679f4047a3e84443d3377be51810f0).

Best,
Kamil

**Comment by aerostitch** [comment]
Awesome, thanks!
