### ISSUE TITLE
Break overlay not visible in Gnome 3.30

### ISSUE THREAD

**Issue by tomasz-oponowicz** [codito/gnome-pomodoro#373]
After upgrading to Gnome 3.30, the break overlay isn't visible.

I tried few scenarios:
- manually trigger a break from the menu
- manually trigger a break from the notification "Take a break!"
- wait until a break is automatically triggered

...in all cases the break overlay isn't visible, i.e. nothing happens.

Version: 0.13.4

**Comment by tomasz-oponowicz** [comment]
I've just noticed there is a patch in the master: https://github.com/codito/gnome-pomodoro/commit/49010bc86705924be259799ae8da1b0c612f1645 Later I will check if it solves the problem.

**Comment by kamilprusko** [comment]
Hi @tomasz-oponowicz ,

Yes, this issue is fixed in master.

**Comment by tomasz-oponowicz** [comment]
@kamilprusko 

I've just tested against the `master` branch. The issue is fixed there. Thanks for your help.

btw. When can we expect next release? Thanks in advance!
