### ISSUE TITLE
"It's time to take break" shakes 

### ISSUE THREAD

**Issue by tomasz-oponowicz** [codito/gnome-pomodoro#376]
## Test case
1. When break starts
1. Then the countdown overlay appears
1. Then there is "It's time to take break" label

### Expected
The "It's time to take break" label is centred.

### Actual
The "It's time to take break" label sometimes moves to the left and returns back after a second. For example when the time is "00:47".

**Comment by jurf** [comment]
This is (I think) because the new Cantarell uses proportional numbers by default. An example how to set it to use tabular numbers can be seen in the GNOME Shell (≥3.28 I think) with the clock.

**Comment by KeyikedalubeNdang** [comment]
Looks like this issue is still open. Noticed that "shaking" behavior the other day. Thought Debian package was the issue.

**Comment by tomasz-oponowicz** [comment]
The issue isn't present in the latest release, 0.16.0. Closing...
