### ISSUE TITLE
Feature Request: Enable extension on application start

### ISSUE THREAD

**Issue by Nearoo** [codito/gnome-pomodoro#389]
I have to enable the extension manually each time I start Pomodoro. It would be nice if that happened automatically. I'm on Ubuntu 18.04.

**Comment by kamilprusko** [comment]
Could you have an older extension installed in a different location? Once extension is enabled, it should stay enabled.

If indicator doesn't show up, check in looking glass (Alt + F2, type: "lg"): Extensions / Pomodoro / View Source. Packaged extension should be in `/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in`.

**Comment by Nearoo** [comment]
It does _stay_ enabled if it is enabled. It's just that when I quit and then start the pomodoro app again, the extension doesn't _get_ enabled.

I checked using the looking glass, it is stored at the location you wrote.

It could very well be that I have two versions installed though. When the timer finishes, I see two `it's time to take a break` interstitial layered on top of each other. Sometimes, but not always, there are also two pomodoro indicators in the gnome shell.

The only installed app from the software center is the pomodoro app though (not the extension from extensions.gnome.org)

**Comment by sojusnik** [comment]
Works fine on Ubuntu 18.10 from the openSUSE repository.

**Comment by Nearoo** [comment]
I don't care anymore.
