### ISSUE TITLE
Unable to maximize the preference window on gnome desktop

### ISSUE THREAD

**Issue by aerostitch** [codito/gnome-pomodoro#394]
Hi,

In https://bugs.debian.org/918024 a user complains that on gnome he's unable to fully maximize the preferences window. Is that an intended behavior? He attached a video of it to the mentioned report.

I'm using it on i3 and don't have any issue maximizing the window.

Thanks
Joseph

**Comment by kamilprusko** [comment]
Hi Joseph,

It's intended. It's not really the main window to be opened for longer.

On his video there is a misleading animation suggesting this window can be maximized - I don't see that in GNOME Shell 3.30.

Best,
Kamil
