### ISSUE TITLE
Tray Icon doesn't appear on manjaro

### ISSUE THREAD

**Issue by yuritoledo** [codito/gnome-pomodoro#398]
Hey man, I'm using your extension (awesome, congrats) in Linux Mint Cinnamon, and the tray icon (applet on Cinnamon) appear on panel, when I open the app at first time. Take a look:

![image](https://user-images.githubusercontent.com/18474538/51312325-23a1bd00-1a32-11e9-8e8e-c311d85999e4.png)

But, yesterday, when  I did a clean install of Manjaro with Cinnamon, the tray icon doesn't appear such as Linux Mint.

I've downloaded the `gnome-shell-pomodoro` and `gnome-pomodoro-git` from AUR, but unsuccesful.

I have `gnome-shell` installed too on Linux Mint, but my co-worker uses Ubuntu Mate (without the `gnome-shell` package), and the tray icon appears too.

So, I don't know what could be.

Thanks :)

**Comment by linuxundich** [comment]
I think this is the same issue like #380 since Manjaro is based on arch.

**Comment by yuritoledo** [comment]
I see... tks
