### ISSUE TITLE
English term in main window

### ISSUE THREAD

**Issue by sojusnik** [codito/gnome-pomodoro#410]
Although my interface is in German, "Short Brake" and "Long Brake" [appear in English](https://i.imgur.com/q8zpQOk.png) in the main window.

Using the 0.14.0-1 version from the openSUSE repository on Ubuntu 18.10.

**Comment by kamilprusko** [comment]
Thanks for reporting

Fixed 8cad4afa447eb2d01237432e1e07429cf21ba784
