### ISSUE TITLE
Gentle pause notification

### ISSUE THREAD

**Issue by ssipos90** [codito/gnome-pomodoro#422]
Hello,

I like the pause overlay, I just don't like it dropping down on me while writing code.
I'd like an option to show the notification 30 seconds (or customizable amount) before the overlay comes down. Either pre-notify before the break or out of the break time, and allow me to finish writing my idea and not break my focus (line of code)

This is an RFC.

Thanks!

**Comment by 04a391c1b7aa** [comment]
Well this is not really an option as changing the value in the preference window. But as a workaround you could use this:

```Diff
diff --git a/plugins/gnome/extension/extension.js b/plugins/gnome/extension/extension.js
index d4450a0..6e04266 100644
--- a/plugins/gnome/extension/extension.js
+++ b/plugins/gnome/extension/extension.js
@@ -43,7 +43,7 @@ const Utils = Extension.imports.utils;
 
 
 // notifications pop up before state changes
-const NOTIFICATIONS_TIME_OFFSET = 10.0;
+const NOTIFICATIONS_TIME_OFFSET = 30.0;
 
 
 var ExtensionMode = {

```

**Comment by ssipos90** [comment]
Thanks, man!
