### ISSUE TITLE
PROBLEM on fedora 29

### ISSUE THREAD

**Issue by mabobakr86** [codito/gnome-pomodoro#425]
the gnome shell extension does not work , it just work as an application  every time i running the application this error appears 
and here is what it said , the program works normally , but this error is annoying 
any Recommendations ?

![Screenshot from 2019-04-28 19-48-24](https://user-images.githubusercontent.com/50082799/56868389-26795a00-69f2-11e9-9250-945e9e385de9.png)

**Comment by tonthon** [comment]
I confirm, I faced the same problem with 
`
gnome-shell-extension-pomodoro-0.15.1-1.fc29.x86_64`

**Comment by okcomputerik** [comment]
Same here (also gnome-shell-extension-pomodoro-0.15.1-1.fc29.x86_64)

**Comment by elbashery** [comment]
yes. The same problem

**Comment by szpak** [comment]
I believe I have encountered the same issue after upgraded to `gnome-shell-extension-pomodoro-0.15.1-1.fc29.x86_64`. The following errors are visible in the system logs:
```
gnome-shell[1956]: WARNING: addSignalMethods is replacing existing [object prototype prototype of GType:Gjs_PomodoroTextIndicator jsobj@(nil)] connect method
gnome-shell[1956]: WARNING: addSignalMethods is replacing existing [object prototype prototype of GType:Gjs_PomodoroTextIndicator jsobj@(nil)] disconnect method
gnome-shell[1956]: WARNING: addSignalMethods is replacing existing [object prototype prototype of GType:Gjs_PomodoroTextIndicator jsobj@(nil)] emit method
gnome-shell[1956]: WARNING: addSignalMethods is replacing existing [object prototype prototype of GType:Gjs_PomodoroIconIndicator jsobj@(nil)] connect method
gnome-shell[1956]: WARNING: addSignalMethods is replacing existing [object prototype prototype of GType:Gjs_PomodoroIconIndicator jsobj@(nil)] disconnect method
gnome-shell[1956]: WARNING: addSignalMethods is replacing existing [object prototype prototype of GType:Gjs_PomodoroIconIndicator jsobj@(nil)] emit method
gnome-shell[1956]: Extension "pomodoro@arun.codito.in" had error: TypeError: GObject.registerClass() used with invalid base class (is PanelMenuButton)
```
Revert to gnome-shell-extension-pomodoro-0.14.0-1.fc29.x86_64 brought it back on.

**Comment by szpak** [comment]
Hmm, I reread the original submission and in my case the plugin didn't start at all. Therefore, it might be another reason. @kamilprusko I can report is as another issue if you prefer.

**Comment by kamilprusko** [comment]
Thanks for bringing this up. 0.15.1 was meant for Fedora 30 / GNOME 3.32...

Quick solution is to downgrade:
```
$ wget https://kojipkgs.fedoraproject.org//packages/gnome-shell-extension-pomodoro/0.14.0/1.fc29/x86_64/gnome-shell-extension-pomodoro-0.14.0-1.fc29.x86_64.rpm
$ sudo dnf downgrade gnome-shell-extension-pomodoro-0.14.0-1.fc29.x86_64.rpm
```

**Comment by szpak** [comment]
I see. @mbooth101 what do you think about an "upgrade" in Fedora repository to make a version built from 0.14.0 the latest for Fedora 29?

**Comment by mbooth101** [comment]
Hmm, I can downgrade in F29 only. I assumed it would be compatible because of the list of gnome shell versions listed here:

https://github.com/codito/gnome-pomodoro/blob/0.15.1/plugins/gnome/extension/metadata.json.in

Is this list incorrect @kamilprusko?

**Comment by kamilprusko** [comment]
@mbooth101 Yes, unfortunately this list is incorrect, I've fixed it in master little too late :( 0.15.1 is for gnome-shell >= 3.32 / F30.

**Comment by mabobakr86** [comment]
I got the solution it works fine for me now , you have to download it from the website not from the firefox gnome extension, i test it from my 1st mail till now and it works fine , anyone had any issue tell me and i’ll help

**Comment by mbooth101** [comment]
@kamilprusko, @szpak -- I submitted a Fedora 29 update reverting back to 0.14.0:

https://bodhi.fedoraproject.org/updates/FEDORA-2019-473cbdd505

Please consider testing it and leaving feedback (3 positive feedbacks will push the update to users automatically, otherwise you have to wait 7 days before I can push it to users)

**Comment by mbooth101** [comment]
> @kamilprusko, @szpak -- I submitted a Fedora 29 update reverting back to 0.14.0:
> 
> https://bodhi.fedoraproject.org/updates/FEDORA-2019-473cbdd505
> 
> Please consider testing it and leaving feedback (3 positive feedbacks will push the update to users automatically, otherwise you have to wait 7 days before I can push it to users)

The update is pushed to testing, you can install and test it by doing:

```
sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2019-473cbdd505
```

**Comment by p3l1gr0** [comment]
This update does not work in F30.

**Comment by mbooth101** [comment]
> This update does not work in F30.
> 
> Ps How do I remove the action done by `sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2019-473cbdd505`

Yes that is expected -- I am surprised you managed to install it because as mentioned above, that update was for F29 only!

This is the F30 update (which contains version 0.15.1):

```
sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2019-d380bfe4bb
```

**Comment by p3l1gr0** [comment]
> Yes that is expected -- I am surprised you managed to install it because as mentioned above, that update was for F29 only!

I thought I should give it a try :)

Now trying the new stuff
 and it works 
![Screenshot from 2019-05-15 14-44-04](https://user-images.githubusercontent.com/50515740/57804276-e7e8dc80-771f-11e9-9037-7200291cd3e3.png)


Thank you

**Comment by p3l1gr0** [comment]
Oops...something is wrong... the clock stays at 24:57 and then the warning "Pomodoro is not responding" appears.
![Screenshot from 2019-05-15 14-48-32](https://user-images.githubusercontent.com/50515740/57804584-a0168500-7720-11e9-9c36-52a139397f0e.png)

**Comment by p3l1gr0** [comment]
Can I assume that the correct way to undo this `sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2019-d380bfe4bb` is something like `sudo dnf upgrade --disablerepo=updates-testing --advisory=FEDORA-2019-d380bfe4bb`?? 
Thanks

**Comment by mbooth101** [comment]
For Fedora 30, the correct version to have is 0.15.1-2.fc30. You can check which version you have using the ```rpm``` command, e.g.:

```
$ rpm -q gnome-shell-extension-pomodoro
gnome-shell-extension-pomodoro-0.15.1-3.fc30.x86_64
```

**Comment by mbooth101** [comment]
@kamilprusko These updates are now pushed to the stable repository, feel free to close this bug :-)

**Comment by kamilprusko** [comment]
Thanks @mbooth101 ! :)

**Comment by tonthon** [comment]
Thanks a lot for the bugfix !!! 

I confirm it now works correctly on fedora 29
gnome-shell-extension-pomodoro-1:0.14.0-3.fc29.x86_64
