### ISSUE TITLE
No settings or preferences menu

### ISSUE THREAD

**Issue by oguzhan-bolukbas** [codito/gnome-pomodoro#431]
I have installed the program for Ubuntu 19.04, Gnome version 3.32.1 with gnome-3.32 branch and I can run it but there is no menu, only timer, stats on top and start button on center. How can I configure the program, how can I reach the menu or preferences? Thanks.
![Screenshot from 2019-08-06 20-28-24](https://user-images.githubusercontent.com/21161568/62562039-1098f200-b889-11e9-96b9-4863b5a9bb3c.png)
![Screenshot from 2019-08-06 20-29-11](https://user-images.githubusercontent.com/21161568/62562054-168ed300-b889-11e9-9a81-97acf7551be6.png)

**Comment by kamilprusko** [comment]
I assume that the indicator is not displaying for some reason... :/

![Screenshot from 2019-08-13 12-27-54](https://user-images.githubusercontent.com/1135423/62935257-ea161200-bdc6-11e9-89d6-0025517efc5d.png)

You may open preferences from command line: `$ gnome-pomodoro --preferences` .

If you have same issue with other apps, you could toggle on Tweaks > Top Bar > Application Menu. For future, moved the app-menu to a hamburger in gnome-3.32 branch.
