### ISSUE TITLE
No stats whatsoever.  [0.14.0 on ubuntu 18.04]

### ISSUE THREAD

**Issue by arooni** [codito/gnome-pomodoro#432]
I have completed multiple pomodoros but only see 

"Nothing to see yet

Complete a few sessions"

What to do?  
Thanks!

**Comment by kamilprusko** [comment]
That has been fixed in ff286e47523caa139408b776d5559f1d2f758c67

You could create a directory `~/.local/share/gnome-pomodoro/` manually or update to a newer version.
