### ISSUE TITLE
Compiles without indicator on Ubuntu 19.04

### ISSUE THREAD

**Issue by ivanguy** [codito/gnome-pomodoro#438]
i found that PKG_CHECK_MODULES(INDICATOR_PLUGIN) in configure.ac:62
should checks for ayatana-appindicator3-0.1
pkg-config output it is named appindicator3-0.1. Changing this configures it with indicator, no luck checking if it works - dunno how to reinstall

**Comment by kamilprusko** [comment]
The configure.ac looks fine. I would expect pkg-config output to be ayatana-appindicator3-0.1... 

You don't need it if you're using GNOME or wayland, this dependency is optional.

**Comment by ivanguy** [comment]
yea, had to enable it in gnome-shell-extensions-prefs, sry

**Comment by ivanguy** [comment]
autogen.sh output 
...
checking for INDICATOR_PLUGIN... no
...
plugins:
    gnome:                  yes
    indicator:              no


autogen.sh output after changing configure.ac:62 
ayatana-appindicator3-0.1 to appindicator3-0.1

...
checking for INDICATOR_PLUGIN... yes
...
plugins:
    gnome:                  yes
    indicator:              yes
