### ISSUE TITLE
Autostart timer at boot

### ISSUE THREAD

**Issue by 04a391c1b7aa** [codito/gnome-pomodoro#443]
Does someone know which line of code I need to add if I want to start the timer automatically after boot?

**Comment by kamilprusko** [comment]
You can use GNOME Tweak Tool for that. It will create a file `~/.config/autostart/org.gnome.Pomdoro.Autostart.desktop`
```
[Desktop Entry]
Type=Application
Exec=gapplication action org.gnome.Pomodoro start-client
NoDisplay=True
```

If you're using GNOME with the extension enabled, then you don't need to. The extension will open the app in background.

**Comment by 04a391c1b7aa** [comment]
Oh sorry, maybe I didn't explain it well enough. The extension starts at boot, but as I use it on my work laptop I would like to also start the timer (i.e. counting down the 25 minutes) immediately at start of the extension.

I guess that would be easy to do if I add some line(s) (maybe `Actions.Trigger.START`? or such) where the extension starts. I tried to search through the code, but as I never worked with a GNOME extension myself I got stuck :/

**Comment by kamilprusko** [comment]
Ok. You can do that by adding `gnome-pomodoro --no-default-window --start` to autostart.

Simplier way would be adding `--start` flag in data/org.gnome.Pomodoro.service.in or `/usr/share/dbus-1/services/org.gnome.Pomodoro.service

If you would change the code, I suggest modifying lib/application.vala `startup()` method. Add `this.timer.start ();` at the end.

**Comment by 04a391c1b7aa** [comment]
Perfect that works! Thanks for your help!
