### ISSUE TITLE
Feature request: Is it possible to add a stop watch? And show "hour:min:seconds" in the panel? Thanks.

### ISSUE THREAD

**Issue by 9527KGG** [codito/gnome-pomodoro#444]
Is it possible to add a stop watch? And show "hour:min:seconds" in the panel? Thanks.

Similar to 
![image](https://user-images.githubusercontent.com/12282281/65823632-a3f9fe00-e20e-11e9-8e75-b5947dc3d6a2.png) (Mac OS menu timer)

Thanksl

**Comment by kamilprusko** [comment]
Time++ extension does that: https://extensions.gnome.org/extension/1238/time/ .

The main idea behind the Pomodoro Technique is time boxing. IMHO a countdown serves that purpose better than a stopwatch, so I won't be adding it. Another reason is that GNOME Clocks has a built-in stopwatch, so there is little reason for another one.

**Comment by 9527KGG** [comment]
Thanks. I use xfc4 instead of gnome. https://extensions.gnome.org/extension/1238/time/  seems not working with xfc4 which is a popular lightweight desktop.

GNOME Clocks cannot show time in the task panel. So it does not work for my case either.

But thanks, anyway.

**Comment by kamilprusko** [comment]
This looks promising https://goodies.xfce.org/projects/panel-plugins/xfce4-stopwatch-plugin

**Comment by 9527KGG** [comment]
Thanks. It does not provide a "apt install" package. I tried to compile it on Ubuntu 18LTS + xfc4. After installing a bunch of software, it still failed pop out error. So I gave up

It would be great if a software such as pomodoro which has "apt install" package to have this feature.
