### ISSUE TITLE
How to update from source

### ISSUE THREAD

**Issue by sojusnik** [codito/gnome-pomodoro#447]
What's the proper way to update to a new version, when Pomodoro is installed from source, as recommended on the [website](https://gnomepomodoro.org/#download), in my case for Ubuntu 19.04?

I've tried the following, but "About" in Pomodoro still shows "0.15.2", although "0.16.0" was released already:

```
git clone -b gnome-3.32 https://github.com/codito/gnome-pomodoro.git
cd gnome-pomodoro

sudo apt-get install autoconf-archive gettext valac pkg-config desktop-file-utils appstream-util libappstream-glib-dev libglib2.0-dev gsettings-desktop-schemas-dev gobject-introspection libgirepository1.0-dev libsqlite3-dev libgom-1.0-dev libgstreamer1.0-dev libgtk-3-dev libcanberra-dev libpeas-dev libappindicator3-dev

./autogen.sh --prefix=/usr --datadir=/usr/share
make
sudo make install
```

**Comment by kamilprusko** [comment]
Hi,

The version in gnome-3.32 branch is ok. 0.16.0 is compatible with gnome-shell 3.34 and not backward compatible with 3.32. So the branches thing saved you from headache ;)

I hope to spare some time to migrate to meson and flatpak... but for compiling from source I think these branches are a better choice than master.

**Comment by sojusnik** [comment]
Good to know, thanks!
