### ISSUE TITLE
Thanks a lot for the latest release! <3

### ISSUE THREAD

**Issue by unsungNovelty** [codito/gnome-pomodoro#469]
This is not a bug or a feature request. 

Just want say thanks for maintaining this not so important seeming _but super important peace of software._ My productivity system is built around this software and it has never disappointed me. It keeps me sane while working long hours learning and doings stuff. SO, Thank you @codito @kamilprusko! :bowing_man: :heart: 

Please close the ticket whenever necessary. :slightly_smiling_face:

**Comment by kamilprusko** [comment]
Thanks so much for your kind message :heart: 

It lifted my spirit in these troubled times.

**Comment by unsungNovelty** [comment]
We need all the love and support we can get during these times @kamilprusko. Stay safe and keep at it! :heart:
