### ISSUE TITLE
gnome-shell-extension-pomodoro is outdated in Fedora repo.

### ISSUE THREAD

**Issue by al-shakib** [codito/gnome-pomodoro#470]
Like title says, Pomodoro is outdated in Fedora repo.

```Name         : gnome-shell-extension-pomodoro
Epoch        : 1
Version      : 0.15.2
Release      : 0.1.gitcb1ad32.fc31
Architecture : x86_64
Size         : 6.0 M
Source       : gnome-shell-extension-pomodoro-0.15.2-0.1.gitcb1ad32.fc31.src.rpm
Repository   : fedora
Summary      : A time management utility for GNOME
URL          : http://gnomepomodoro.org/
License      : GPLv3+
Description  : This GNOME utility helps to manage time according to Pomodoro Technique.
             : It intends to improve productivity and focus by taking short breaks

**Comment by kamilprusko** [comment]
@mbooth101 I'll be grateful if you upload new releases.

[0.16.0](https://github.com/codito/gnome-pomodoro/releases/tag/0.16.0) for Fedora 31
[0.17.0](https://github.com/codito/gnome-pomodoro/releases/tag/0.17.0) for Fedora 32

**Comment by mbooth101** [comment]
Sure, I submitted two updates that should be pushed to testing in a day or so:

F31: https://bodhi.fedoraproject.org/updates/FEDORA-2020-540911b5f9
F32: https://bodhi.fedoraproject.org/updates/FEDORA-2020-1beb4442c8

Please consider testing and leaving feedback on the updates to get them pushed to stable sooner.

**Comment by kamilprusko** [comment]
Thanks Mat! :)

**Comment by andrm** [comment]
How can I try it out on F31? Automated Tests says it has an error.

**Comment by mbooth101** [comment]
If you follow the link, you can see the installation instructions. I'll repeat it here for F31:

```
sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-540911b5f9
```

However it probably has not yet reached all the mirrors, so if you can't install it now, try again later.

**Comment by Frivolous2** [comment]
On Fedora 32, the version provided is 0.17.0, which appears to be the latest.
