### ISSUE TITLE
Strange icon glitches on Linux Mint 19.3 Cinnamon

### ISSUE THREAD

**Issue by Acmpo6ou** [codito/gnome-pomodoro#476]
I have installed Pomodoro on Linux Mint 19.3 and I have problem with icon:
![Screenshot from 2020-04-20 15-49-03](https://user-images.githubusercontent.com/49025838/79753498-b197e200-831e-11ea-9001-3bdcac6ee977.png)
It looks pretty strange.
When I launch Pomodoro through terminal:
`~$ gnome-pomodoro`
I see this errors:
```
** (gnome-pomodoro:11403): WARNING **: 15:52:07.648: indicator-capability.vala:117: Could not find theme directory "/usr/share/gnome-pomodoro/indicator/Mint-Y-Dark"

(gnome-pomodoro:11403): Gdk-CRITICAL **: 15:52:08.065: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```
Please help, how can I solve this?
Thank you!

**Comment by kamilprusko** [comment]
Logs will rather be related to appindicator3 / ayatana-appindicator3, which is actually handling the icon.

My guess, icon is expected to be larger. I don't have Linux Mint to test this - you may try extracting icons from [Mint-Y-Dark.zip](https://github.com/codito/gnome-pomodoro/files/4504604/Mint-Y-Dark.zip) into `/usr/share/gnome-pomodoro/indicator/Mint-Y-Dark/` , then quit and reopen the app.

**Comment by kamilprusko** [comment]
Btw. If you're running Cinnamon, this applet may be better integrated with your desktop:
https://cinnamon-spices.linuxmint.com/applets/view/131

**Comment by Acmpo6ou** [comment]
> Btw. If you're running Cinnamon, this applet may be better integrated with your desktop:
> https://cinnamon-spices.linuxmint.com/applets/view/131

Thanks it really helped. Do you want me to close issue or to leave it opened?
