### ISSUE TITLE
Resuming Broken After Break

### ISSUE THREAD

**Issue by Ih0rko** [codito/gnome-pomodoro#485]
Hello,

After upgrading to Fedora 32 I'm experiencing issues with unlocking screen after pomodoro break was finished. I've found description here:
https://www.gitmemory.com/issue/codito/gnome-pomodoro/466/610641015

I can add that issue is triggered with Wayland session too. And in logs the following message is present:
```
JS ERROR: Extension pomodoro@arun.codito.in: Error: No signal 'count-updated' on object 'Gjs_pomodoro_arun_codito_in_notifications_PomodoroSource'
                                                  _onTimerUpdate@/usr/share/gnome-shell/extensions/pomodoro@arun.codito.in/notifications.js:604:29
```

This message was really removed in commit 10acd4e95db0f111bf431727e6de3e2e3c8046ab.

Unfortunately it's not root cause because after removing blocks with emit('count-updated') another error logs appeared. I'll post them later because it was on another machine.

**Comment by sojusnik** [comment]
Did you look [here](https://github.com/codito/gnome-pomodoro/issues/466)?

**Comment by Ih0rko** [comment]
Sorry, I'll add my findings to original issue.
