### ISSUE TITLE
Fullscreen countdown and notification don't work on Pop!_OS 20.04

### ISSUE THREAD

**Issue by AnkushMalaker** [codito/gnome-pomodoro#498]
Working features: Indicator, timers, bells
Not working: notifications and full screen timers

Installed the extention using 
`sudo apt-get install gnome-shell-pomodoro`

Any fixes or workarounds would be great. Hardly any way of knowing when the sessions begin and end without the notifications/full screen timers.

**Comment by AnkushMalaker** [comment]
reinstalling and disabling desktop integration resolved the issue. Closing.

**Comment by gilsondev** [comment]
You run the app out of extension right?

**Comment by AnkushMalaker** [comment]
@gilsondev the desktop integration causes problems. I run the app from the app drawer and then operate it using the icon that appears on my tray.
First do a clean uninstall of the app if you installed it via gnome extensions, and then install it via apt install. In my case, logging out, logging back in and then disabling desktop integration restored the notifications as well as full screen timer.
