### ISSUE TITLE
Extension does not work on Gnome 3.38

### ISSUE THREAD

**Issue by sanjayankur31** [codito/gnome-pomodoro#516]
Hello,

On Fedora 33 with gnome 3.38, the extension no longer works:

```
Sep 21 20:18:50 ankur gnome-software[2196]: not handling error not-supported for action search: shell extensions no longer supported
Sep 21 20:18:53 ankur gnome-pomodoro[14007]: gnome-shell-extension.vala:404: Extension error: No JS module 'tweener' found in search path
Sep 21 20:18:53 ankur gnome-pomodoro[14007]: application.vala:211: Failed to initialize plugin "gnome": Operation was cancelled
```

**Comment by yerbestpal** [comment]
This issue is also present on Ubuntu 20.10 Daily, so it definitely seems to specifically affect Gnome 3.38.

**Comment by Keyikedalube** [comment]
Same issue on Debian sid (GNOME 3.38)
```
** (gnome-pomodoro:1810): CRITICAL **: 17:13:42.928: gnome-shell-extension.vala:314: GDBus.Error:org.freedesktop.DBus.Error.NotSupported: ReloadExtension is deprecated and does not work
```

**Comment by fernandogobah** [comment]
+1
Debian SID
Gnome 3.38

**Comment by nariox** [comment]
I have implemented the fix for 3.38. (#517), meanwhile, you can also use the extension from my fork. (:

**Comment by Keyikedalube** [comment]
@nariox Can't test on my side. I'd love to know the output feedback on your PR from others :)

```
./configure: line 2479: syntax error near unexpected token `git-directory'
./configure: line 2479: `AX_IS_RELEASE(git-directory)'
```

**Comment by kaushalyap** [comment]
Issue exists in Fedora 33 beta, (Gnome Shell 3.38.0)

**Comment by sanjayankur31** [comment]
This is fixed in the new release. PR for Fedora 33 opened here: https://src.fedoraproject.org/rpms/gnome-shell-extension-pomodoro/pull-request/2

I'll close this ticket here.

**Comment by llabusch93** [comment]
Will this also find it's way into Ubuntu 20.10?
