### ISSUE TITLE
Desktop integration - error loading extension

### ISSUE THREAD

**Issue by imareo** [codito/gnome-pomodoro#521]
No indicator in top bar (fedora 33, gnome 3.38.1)
Gnome tweak - Extensions -Pomodoro - Error loading extension

**Comment by rcdeoliveira** [comment]
Maybe this is related with #520

**Comment by arnogon** [comment]
See my comment [here](https://github.com/codito/gnome-pomodoro/issues/520#issuecomment-715632651).

**Comment by imareo** [comment]
worked after system update. close
