### ISSUE TITLE
[Question] Can I install the latest version in Ubuntu 20.04?

### ISSUE THREAD

**Issue by lonix1** [codito/gnome-pomodoro#529]
I'm using Ubuntu 20.04.

I can only install (via `apt install gnome-shell-pomodoro`) version 0.16.0, whereas the latest is 0.18.0.

Has anyone managed to install the latest version?

(I know I can build from source, but prefer not to.)

**Comment by lonix1** [comment]
Okay I see it [isn't available](https://launchpad.net/ubuntu/+source/gnome-shell-pomodoro).

It's a pity as focal/20.04 is the latest LTS version.

**Comment by lonix1** [comment]
@aerostitch Are you the maintainer of the apt package? What needs to be done to enable v18 on ubuntu20?

**Comment by aerostitch** [comment]
Hi, I maintain it in Debian and I can see from your link that 0.18.0 has been available in the Ubuntu repos since Nov. 10th, so it should be a matter of updating your repo probably? I'm not familiar with the release process in Ubuntu.

**Comment by lonix1** [comment]
It's only available in the latest ubuntu beta unfortunately.

Nonetheless, thanks for confirming, and sorry to trouble you. I saw your name on there so I wrongly assumed you were the packager.

**Comment by roman-eonx** [comment]
So, how can we get the latest versions (0.17 or 0.18) on Ubuntu Focal (20.04)?
