### ISSUE TITLE
Need splash screen time on extension mode when in break + some enhancement 

### ISSUE THREAD

**Issue by MohiuddinSumon** [codito/gnome-pomodoro#531]
When I use pomodoro as an extension I like it more than app version, But extension mode lacks the splash screen feature. If you can integrate splash screen timer in extension then it would be batter.

Also if splash screen can be locked (optional) then it will be more effective.  

App can have extension like peek timer and pause stop button, that's more efficient 

when device is locked , pomodoro should be paused , and unlocking should resume with a notification

**Comment by aouini-oussama** [comment]
@MohiuddinSumon am really happy to find some one that thought the same as me :), so did you find the solution

**Comment by MohiuddinSumon** [comment]
Currently using this : https://github.com/roldanjr/pomatez
