### ISSUE TITLE
Option to display icon only.

### ISSUE THREAD

**Issue by 0rAX0** [codito/gnome-pomodoro#58]
Is there a possibility to have an option to display icon-only: always | when inactive | none?

**Comment by eldelacajita** [comment]
I would suggest the option of using a visual timer instead of digits. A interactive icon, like a small progress bar or a circular progress indicator. Or a changing color.

**Comment by kamilprusko** [comment]
Thanks @eldelacajita for your suggestion. It's already done in master branch, see #156. I'll close both tickets once this feature is released.

**Comment by eldelacajita** [comment]
That is a great solution, indeed. Thank you!

**Comment by PanderMusubi** [comment]
Yes, your suggestion for a circle in https://cloud.githubusercontent.com/assets/1135423/4603978/15661b7e-5181-11e4-93a3-81d510424420.png is very nice. Makes the screen more quiet and prevent people for mistaking the pomodoro timer for the actual time. :+1:

**Comment by kamilprusko** [comment]
It's released for GNOME 3.14 and 3.16.
