### ISSUE TITLE
Ability to execute script on break/resume

### ISSUE THREAD

**Issue by danthegoodman** [codito/gnome-pomodoro#70]
I would like to be able execute a script when the timer finished or resumes. Specifically, I'm wanting to pause/play my music player, but I can imagine other actions being useful.

I'm thinking either have two scripts, one for break and one for resume, or just have one and pass in arguments to the script.

    myscript [break|resume] [short|long]

**Comment by kaptoxic** [comment]
+1 for this feature. It would be tremendously helpful...

**Comment by kamilprusko** [comment]
I've drafted ui for this.

![screenshot from 2016-09-09 19-18-25](https://cloud.githubusercontent.com/assets/1135423/18396341/64e85252-76c3-11e6-93b6-4bb6b5da9c68.png)

![screenshot from 2016-09-09 19-19-07](https://cloud.githubusercontent.com/assets/1135423/18396355/70fa95aa-76c3-11e6-9d71-eb0cea0ae128.png)

There would be no distinction between long and a short break, because I it could be unpredictable when switching breaks.

Comments are welcome.

**Comment by kaptoxic** [comment]
The UI looks great and I think it would do the job very well. Now, for the distinction between short/long breaks, it seems it might indeed be useful (e.g. for people that do tracking). I wonder why it would be unpredictable and whether it can be easily solved (with something like a flag that could designate short/long break).
Also, would it be tricky to include some special variables that designate what actually triggered the script (e.g. like $type and could be "pomodoro-start" or "pause-stop")? This would allow passing these variables as command line arguments e.g.

**Comment by kamilprusko** [comment]
Thanks @kaptoxic for feedback.

It could be not intuitive when switching breaks. Both "skip" and "start" events would be triggered, and in case of transient / non-stateful actions like sound notifications this could be an issue... But indeed, having distinction between breaks probably is be more important.

Possible solution would be to let this be handled by scripts, or make distinction between short-break, long-break and any-break, but I haven't came up with reasonable ui for this.

Variables should be easy to add. I think of stealing "Add" button idea from new renaming tool in nautilus
![image](https://cloud.githubusercontent.com/assets/1135423/18419074/bcb6144c-7853-11e6-857c-d560dcc55e1c.png)

So far I came up with 3-5 variables

* state
* elapsed
* duration
* previous-state / next-state (if available)

As to passing trigger type, action may be triggered by several triggers at a time so would need to be passed as list (comma separated)... or similar thing could be achieved by option to duplicate actions if you're willing to hook up different scripts to certain triggers.

**Comment by kaptoxic** [comment]
I see. Indeed, this sounds good and the UI is awesome. :+1:

**Comment by kamilprusko** [comment]
Added in 64f80e1db753a72c2bfc6cbdb99777da8175bba9

**Comment by grindhold** [comment]
@kamilprusko there is an unclaimed $20 bounty on bountysource for this issue. just saying :)
https://www.bountysource.com/issues/1198632-ability-to-execute-script-on-break-resume

**Comment by smichel17** [comment]
*/takes the excuse to mention https://wiki.snowdrift.coop/market-research/other-crowdfunding#bounty*

**Comment by kamilprusko** [comment]
Thanks guys, but I'll pass. I appreciate the feedback and support on this feature :)
