### ISSUE TITLE
Keyboard shortcuts for toggling timer state

### ISSUE THREAD

**Issue by codito** [codito/gnome-pomodoro#9]
Add keyboard shortcuts to toggle pomodoro timer state. Make it optional for the user (i.e. available only if GIR bindings for libkeybinder3 are installed in system).

**Comment by postadelmaga** [comment]
Sorry for revamp this old thread.

Is there any shortcut for play/pause ?

On the last version I can only find CTRL + ALT + P for start/stop but this reset the timer all time ... I am new to 'pomodoro philosophy' but I feel this feature would be more useful than start/stop ...

**Comment by kamilprusko** [comment]
@postadelmaga or maybe turn it to start/pause/resume. I think that having a single shortcut is better than two, it avoids confusion which one to use.

**Comment by smichel17** [comment]
I would have two shortcuts: [play/pause] and stop.
