### ISSUE TITLE
Hotkey setting

### ISSUE THREAD

**Issue by pztrick** [codito/gnome-pomodoro#96]
Right now, `Ctrl Alt P` starts/stops the timer. This is great, except that you cannot configure it in the settings and it captures the hotkey ahead of any other program you may use that also binds the hotkey. _(For instance, the popular editor Sublime Text 2 uses `Ctrl Alt P` as a key binding and this breaks that functionality.)_

I was able to successfully change the hotkey by modifying the XML schema and running `glib-compile-schemas schemas/` in the extension folder (and reloading shell) -- but it could be made available for configuration in the settings. Hence the issue :)

**Comment by babisp** [comment]
Hello! I need to re-open this, as I can't find a way to fix this on the current version. I'm using Ubuntu 18.04. Thanks in advance
